// @generated by next-prisma-flow-state-engine
// file: server/actions.ts

"use server";

import { prisma } from "../../prisma";
import {
  invalidateTags,
  keys,
  FlowCtx,
  FlowPolicyError,
  FlowValidationError,
} from "../../core";
import { canComment } from "../../policies";
import { CommentSelect } from "./selects";
import { CommentCreateSchema, CommentUpdateSchema } from "../types/schemas";
import type { FlowCommentCreate, FlowCommentUpdate } from "../types/schemas";
import {
  transformCommentCreate,
  transformCommentUpdate,
} from "../types/transforms";

// Transform Prisma response to match FlowPost schema (null -> undefined for relations)
function transformResponse(item: any): any {
  if (!item) return item;
  const result = { ...item };
  return result;
}

export async function createComment(
  data: FlowCommentCreate,
  ctx: FlowCtx = {},
) {
  const policy = await canComment("create", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const parsed = CommentCreateSchema.safeParse(data);
  if (!parsed.success) {
    throw new FlowValidationError(parsed.error.issues);
  }

  const createData = transformCommentCreate(parsed.data as any);
  const item = await prisma.comment.create({
    data: { ...createData, ...policy.data },
    select: CommentSelect,
  });

  await invalidateTags([keys.m("Comment").tag()]);
  return transformResponse(item);
}

export async function updateComment(
  id: string,
  data: FlowCommentUpdate,
  ctx: FlowCtx = {},
) {
  const policy = await canComment("update", ctx || {}, id);
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const parsed = CommentUpdateSchema.safeParse(data);
  if (!parsed.success) {
    throw new FlowValidationError(parsed.error.issues);
  }

  const updateData = transformCommentUpdate(parsed.data as any);
  const item = await prisma.comment.update({
    where: { id: id, ...policy.where },
    data: { ...updateData, ...policy.data },
    select: CommentSelect,
  });

  await invalidateTags([
    keys.m("Comment").tag(),
    keys.m("Comment").tag(String(id)),
  ]);
  return transformResponse(item);
}

export async function deleteComment(id: string, ctx?: FlowCtx) {
  const policy = await canComment("delete", ctx || {}, id);
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  await prisma.comment.delete({
    where: { id: id, ...policy.where },
  });

  await invalidateTags([
    keys.m("Comment").tag(),
    keys.m("Comment").tag(String(id)),
  ]);
}
