// @generated by next-prisma-flow-state-engine
// file: server/queries.ts

"use server";

import { prisma } from "../../prisma";
import { cacheTagged, FlowCtx, FlowPolicyError } from "../../core";
import { canComment } from "../../policies";
import { CommentSelect } from "./selects";
import type { Prisma } from "../../prisma";

// Transform Prisma response to match FlowComment schema (null -> undefined for relations)
function transformResponse(item: any): any {
  if (!item) return item;
  const result = { ...item };
  return result;
}

function transformResponseList(items: any[]): any[] {
  return items.map(transformResponse);
}

export const getCommentById = cacheTagged(async function (
  id: string,
  ctx: FlowCtx = {},
) {
  const policy = await canComment("read", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const item = await prisma.comment.findUnique({
    where: { id: id, ...policy.where },
    select: CommentSelect,
  });

  return transformResponse(item);
});

export type CommentListParams = {
  where?: Prisma.CommentWhereInput;
  orderBy?:
    | Prisma.CommentOrderByWithRelationInput
    | Prisma.CommentOrderByWithRelationInput[];
  skip?: number;
  take?: number;
  cursor?: Prisma.CommentWhereUniqueInput;
};

export const listComments = cacheTagged(async function (
  params: CommentListParams = {},
  ctx: FlowCtx = {},
) {
  const policy = await canComment("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const where = { ...params.where, ...policy.where };

  const [items, total] = await Promise.all([
    prisma.comment.findMany({
      where,
      orderBy: params.orderBy,
      skip: params.skip,
      take: params.take || 50,
      cursor: params.cursor,
      select: CommentSelect,
    }),
    prisma.comment.count({ where }),
  ]);

  return { items: transformResponseList(items), total };
});

export const searchComments = cacheTagged(async function (
  query: string,
  params: Omit<CommentListParams, "where"> = {},
  ctx: FlowCtx = {},
) {
  const policy = await canComment("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const where = {
    AND: [
      policy.where,
      {
        OR: [
          { content: { contains: query, mode: "insensitive" as const } },
          { postId: { contains: query, mode: "insensitive" as const } },
          { authorId: { contains: query, mode: "insensitive" as const } },
        ],
      },
    ],
  };

  const [items, total] = await Promise.all([
    prisma.comment.findMany({
      where,
      orderBy: params.orderBy,
      skip: params.skip,
      take: params.take || 50,
      cursor: params.cursor,
      select: CommentSelect,
    }),
    prisma.comment.count({ where }),
  ]);

  return { items: transformResponseList(items), total };
});
