// @generated by next-prisma-flow-state-engine
// file: index.ts

// Tree-shakeable named exports
export * as CompanyServer from "./server";
export * as CompanyClient from "./client";
export * as CompanyTypes from "./types";

// Direct exports for common usage
export {
  // Hooks
  useCompany,
  useCompanyList,
  useCreateCompany,
  useUpdateCompany,
  useDeleteCompany,
  useCompanyMutation,
} from "./client/hooks";

export {
  // Forms
  useCompanyForm,
  useCompanyQuickForm,
  type CompanyFormOptions,
  type CompanyFormProps,
} from "./client/forms";

export {
  // Schemas
  CompanyCreateSchema,
  CompanyUpdateSchema,
  CompanyFilterSchema,
  type FlowCompany,
  type FlowCompanyCreate,
  type FlowCompanyUpdate,
  type FlowCompanyFilter,
} from "./types/schemas";

export {
  // Types
  type CompanyWithRelations,
  type CompanyListItem,
  type CompanyPage,
  type CompanyCursor,
} from "./types/types";

// Server-only exports (for server components/actions)
export type { CompanyListParams } from "./server/queries";
