// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-08-02T12:30:43.228Z

import { useCallback, useState } from "react";
import { useAtomValue, useSetAtom } from "jotai";
import type { IFuseOptions } from "fuse.js";
import { entityAtomFamily, errorAtom, pendingPatchesAtom } from "./atoms";
import {
	countAtom,
	countByFieldAtomFamily,
	entityBusyFamily,
	entityLoadableFamily,
	hasAnyAtom,
	listByFieldAtomFamily,
	listLoadable,
	loadingAtom,
	pagedAtom,
	searchAtom,
	selectedAtom,
	selectedIdAtom,
} from "./derived";

import { makeRelationHelpers } from "../shared/hooks/relation-helper";
import { createFormActions, makeUseFormHook, type UseFormOptions } from "../shared/hooks/use-form-factory";
import { useAutoload } from "../shared/hooks/useAutoload";
import { createAtom, deleteAtom, loadEntityAtom, loadsListAtom, updateAtom, upsertAtom } from "./fx";
import { schemas } from "./schemas";
import type { CreateInput, ModelType, Relationships, UpdateInput } from "./types";

/**
 * Hook for managing the complete todolists collection with comprehensive state management.
 *
 * Provides access to the full todolists list along with loading states, error handling,
 * and all necessary CRUD operations. This hook manages the global state for todolists
 * and automatically handles loading indicators and error states.
 *
 * @param {Object} opts - Configuration options
 * @param {boolean} [opts.autoLoad=true] - Whether to automatically load data when component mounts
 *
 * @returns {Object} Complete todolists management interface
 * @returns {Array} data - Array of todolists (empty array when loading or on error)
 * @returns {number} count - Total number of todolists available
 * @returns {boolean} hasAny - Quick check if any todolists exist
 * @returns {boolean} loading - True when fetching data or performing operations
 * @returns {Error|null} error - Last error that occurred, null if no errors
 * @returns {Function} createTodoList - Creates a new todolist
 * @returns {Function} updateTodoList - Updates an existing todolist
 * @returns {Function} upsertTodoList - Upserts a todolist
 * @returns {Function} deleteTodoList - Deletes a todolist by ID
 * @returns {Function} fetchAll - Refreshes the entire todolists list
 *
 * @example
 * ```tsx
 * function TodoListsList() {
 *   const { data, loading, error, createTodoList, updateTodoList, deleteTodoList } = useTodoListsList();
 *
 *   if (loading) return <div>Loading todolists...</div>;
 *   if (error) return <div>Error: {error.message}</div>;
 *
 *   return (
 *     <div>
 *       {data.map(todolist => (
 *         <TodoListItem key={todolist.id} todolist={todolist} onUpdate={updateTodoList} onDelete={deleteTodoList} />
 *       ))}
 *     </div>
 *   );
 * }
 * ```
 */
export function useTodoListsList(opts: { autoLoad?: boolean } = { autoLoad: true }) {
	const loadable = useAtomValue(listLoadable);
	const busy = useAtomValue(loadingAtom);
	const count = useAtomValue(countAtom);
	const hasAny = useAtomValue(hasAnyAtom);
	const lastError = useAtomValue(errorAtom);

	const createTodoList = useSetAtom(createAtom);
	const updateTodoList = useSetAtom(updateAtom);
	const deleteTodoList = useSetAtom(deleteAtom);
	const upsertTodoList = useSetAtom(upsertAtom);
	const fetchAll = useSetAtom(loadsListAtom);
	const fetchById = useSetAtom(loadEntityAtom);

	useAutoload(
		() => opts.autoLoad !== false && !busy && !hasAny,
		() => fetchAll(),
	);

	return {
		/* data */
		data: loadable.state === "hasData" ? loadable.data : [],
		count,
		hasAny,

		/* meta */
		loading: busy || loadable.state === "loading",
		error: loadable.state === "hasError" ? loadable.error : lastError,

		/* actions */
		createTodoList,
		updateTodoList,
		deleteTodoList,
		upsertTodoList,
		fetchAll,
		fetchById,
	};
}

/**
 * Hook for managing a specific todolist by ID with optimistic updates and error handling.
 *
 * Provides granular control over individual todolists, including fetching, updating, and deleting.
 * The hook automatically manages loading states and errors specific to this todolist instance.
 * Actions are pre-bound with the todolist ID for convenience.
 *
 * @param {string} id - The unique identifier of the todolist to manage
 * @param {Object} opts - Configuration options
 * @param {boolean} [opts.autoLoad=true] - Whether to automatically load data when component mounts
 *
 * @returns {Object} Single todolist management interface
 * @returns {Object|null} data - The todolist data object, null if not found or loading
 * @returns {boolean} loading - True when fetching or performing operations on this todolist
 * @returns {Error|null} error - Last error related to operations on this todolist
 * @returns {Function} updateTodoList - Updates this specific todolist with provided data
 * @returns {Function} deleteTodoList - Deletes this specific todolist
 * @returns {Function} fetch - Fetches/refreshes this specific todolist from the server
 * @returns {Object} relations - relationship helpers
 *
 * @example
 * ```tsx
 * function TodoListDetail({ todolistId }: { todolistId: string }) {
 *   const { data, loading, error, updateTodoList, deleteTodoList } = useTodoList(todolistId);
 *
 *   if (loading) return <div>Loading todolist...</div>;
 *   if (error) return <div>Error loading todolist: {error.message}</div>;
 *   if (!data) return <div>TodoList not found</div>;
 *
 *   const handleSave = (formData) => {
 *     updateTodoList(formData); // ID is automatically included
 *   };
 *
 *   return (
 *     <div>
 *       <h1>{data.title}</h1>
 *       <p>{data.content}</p>
 *       <button onClick={() => deleteTodoList()}>Delete</button>
 *     </div>
 *   );
 * }
 * ```
 */
export function useTodoList(id: string, opts: { autoLoad?: boolean } = { autoLoad: true }) {
	const todolist = useAtomValue(entityAtomFamily(id));
	const loadable = useAtomValue(entityLoadableFamily(id));
	const busyItem = useAtomValue(entityBusyFamily(id));
	const lastError = useAtomValue(errorAtom);
	const pendingPatches = useAtomValue(pendingPatchesAtom);

	const updateTodoList = useSetAtom(updateAtom);
	const deleteTodoList = useSetAtom(deleteAtom);
	const fetch = useSetAtom(loadEntityAtom);

	const relations = makeRelationHelpers<Relationships>(id, updateTodoList);

	useAutoload(
		() => opts.autoLoad !== false && !busyItem && !todolist && !pendingPatches[id],
		() => fetch({ id }),
	);

	return {
		/* data */
		data: todolist,

		/* meta */
		loading: busyItem || loadable.state === "loading",
		error: lastError,

		/* actions */
		updateTodoList: (data: UpdateInput) => updateTodoList({ id, data }),
		deleteTodoList: () => deleteTodoList(id),
		fetch: () => fetch({ id }),

		/* relations */
		relations,
	};
}

/**
 * Enhanced form hook with integrated CRUD operations and optimistic updates.
 *
 * Automatically detects create vs update mode based on whether an instance is provided.
 * Integrates directly with the todolist atoms for seamless state management.
 *
 * @param {ModelType} [instance] - TodoList instance for update mode, undefined for create mode
 * @param {Object} [options] - Form options and callbacks
 * @param {Function} [options.onSuccess] - Callback fired on successful submission
 * @param {Function} [options.onError] - Callback fired on submission error
 * @param {boolean} [options.resetOnSuccess=true] - Whether to reset form after successful creation
 * @param {Object} [options.transform] - Data transformation functions
 *
 * @returns {Object} Enhanced form interface with submission handling
 * @returns {Function} handleSubmit - Form submission handler
 * @returns {boolean} isSubmitting - Whether form is currently submitting
 * @returns {boolean} isCreating - Whether form is in create mode and submitting
 * @returns {boolean} isUpdating - Whether form is in update mode and submitting
 * @returns {string} mode - Current form mode: 'create' | 'update'
 * @returns {any} submitError - Last submission error, if any
 * @returns {*} ...formMethods - All react-hook-form methods and state
 *
 * @example
 * ```tsx
 * function TodoListForm({ todolist, onClose }) {
 *   const form = useTodoListForm(todolist, {
 *     onSuccess: () => onClose(),
 *     onError: (error) => toast.error(error.message),
 *     transform: {
 *       toCreateInput: (data) => ({
 *         ...data,
 *         authorId: data.author?.id || data.authorId,
 *         categoryId: data.category?.id || data.categoryId,
 *       }),
 *     },
 *   });
 *
 *   return (
 *     <form onSubmit={form.handleSubmit}>
 *       <input {...form.register('title')} placeholder="Title" />
 *       <textarea {...form.register('description')} placeholder="Description" />
 *       <button type="submit" disabled={form.isSubmitting}>
 *         {form.isSubmitting
 *           ? (form.mode === 'create' ? 'Creating...' : 'Updating...')
 *           : (form.mode === 'create' ? 'Create TodoList' : 'Update TodoList')
 *         }
 *       </button>
 *     </form>
 *   );
 * }
 * ```
 */
export function useTodoListForm(instance?: ModelType, options: UseFormOptions<ModelType> = {}) {
	const createTodoListAction = useSetAtom(createAtom);
	const updateTodoListAction = useSetAtom(updateAtom);

	const formActions = createFormActions(createTodoListAction, updateTodoListAction);

	return makeUseFormHook<ModelType, CreateInput, UpdateInput>(
		{
			create: schemas.createInput,
			update: schemas.updateInput,
		},
		formActions,
	)(instance, options);
}

export const useSelectedId = () => useAtomValue(selectedIdAtom);
export const useSelected = () => useAtomValue(selectedAtom);
export const useSetSelectedId = () => useSetAtom(selectedIdAtom);

export function useListByFieldValue<K extends keyof ModelType>(field: K, value: ModelType[K]) {
	const fam = listByFieldAtomFamily(field);
	return useAtomValue(fam(value));
}

export function usePagedList(page: number, pageSize = 10) {
	return useAtomValue(pagedAtom({ page, pageSize }));
}

// Type helper to extract all string paths from a type
type PathsToStringProps<T, P extends string = ""> = T extends string | number | boolean | Date | null | undefined
	? P
	: T extends Array<infer U>
		? PathsToStringProps<U, P>
		: T extends object
			? {
					[K in keyof T]: PathsToStringProps<T[K], P extends "" ? K & string : `${P}.${K & string}`>;
				}[keyof T]
			: never;

// Get all valid search keys for ModelType
type SearchKeys = PathsToStringProps<ModelType>;

interface UseSearchOptions extends Omit<IFuseOptions<ModelType>, "keys"> {
	keys?: SearchKeys[];
}

interface UseSearchReturn<T> {
	search: (query: string) => void;
	results: T[];
	query: string;
}

export function useSearch(options?: UseSearchOptions): UseSearchReturn<ModelType> {
	const [query, setQuery] = useState("");
	const results = useAtomValue(searchAtom({ query, options }));

	const search = useCallback((newQuery: string) => {
		setQuery(newQuery);
	}, []);

	return {
		search,
		results,
		query,
	};
}

export function useCountByFieldValue<K extends keyof ModelType>(field: K, value: ModelType[K]) {
	const fam = countByFieldAtomFamily(field);
	return useAtomValue(fam(value));
}
