// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-08-02T12:01:55.930Z

import {
	TodoCreateManyInputSchema,
	TodoFindFirstArgsSchema,
	TodoFindManyArgsSchema,
	TodoUncheckedCreateInputSchema,
	TodoUncheckedUpdateInputSchema,
	TodoWhereInputSchema,
	TodoWhereUniqueInputSchema,
} from "../zod";

export const schemas = {
	whereUnique: TodoWhereUniqueInputSchema,
	where: TodoWhereInputSchema,
	createInput: TodoUncheckedCreateInputSchema,
	createManyInput: TodoCreateManyInputSchema,
	updateInput: TodoUncheckedUpdateInputSchema,
	findFirstArgs: TodoFindFirstArgsSchema,
	findManyArgs: TodoFindManyArgsSchema,
};
