// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-08-02T12:30:43.227Z

import type { Prisma } from "../prisma";

export type CreateInput = Prisma.TodoUncheckedCreateInput;
export type CreateManyInput = Prisma.TodoCreateManyInput;
export type UpdateInput = Prisma.TodoUncheckedUpdateInput;
export type UpdateManyInput = {
	where: Prisma.TodoWhereInput;
	data: Prisma.TodoUncheckedUpdateManyInput;
	limit?: number;
};
export type WhereInput = Prisma.TodoWhereInput;
export type WhereUniqueInput = Prisma.TodoWhereUniqueInput;
export type OrderByInput = Prisma.TodoOrderByWithRelationInput;
export type SelectInput = Prisma.TodoSelect;
export type IncludeInput = Prisma.TodoInclude;

export type ModelType = Prisma.TodoGetPayload<{
	select: {
		id: true;
		title: true;
		completed: true;
		createdAt: true;
		updatedAt: true;
	};
}>;

export type Options = {
	orderBy?: OrderByInput;
};

export type CreateManyOptions = {
	include?: IncludeInput;
	select?: SelectInput;
};

export interface Relationships extends Record<string, { where: any; many: boolean }> {
	todoList: { where: Prisma.TodoListWhereUniqueInput; many: false };
}
