// @generated by next-prisma-flow-state-engine
// file: client/hooks.ts

"use client";

import {
  useQuery,
  useMutation,
  useQueryClient,
  UseQueryOptions,
  UseMutationOptions,
} from "@tanstack/react-query";
import { useState, useCallback } from "react";
import { keys } from "../../core/keys";
import { useFlowCtx } from "../../core/provider";
import type { CommentListParams } from "../server/queries";
import type {
  FlowComment,
  FlowCommentCreate,
  FlowCommentUpdate,
} from "../types/schemas";

export function useComment(
  id: string,
  options?: Omit<UseQueryOptions<FlowComment | null>, "queryKey" | "queryFn">,
) {
  const ctx = useFlowCtx();

  return useQuery({
    queryKey: keys.m("Comment").byId(String(id)),
    queryFn: async () => {
      const { getCommentById } = await import("../server/queries");
      return getCommentById(id, ctx);
    },
    ...options,
  });
}

export function useCommentList(
  params?: CommentListParams,
  options?: Omit<
    UseQueryOptions<{ items: FlowComment[]; total: number }>,
    "queryKey" | "queryFn"
  >,
) {
  const ctx = useFlowCtx();
  const [localParams, setLocalParams] = useState(params || {});

  const query = useQuery({
    queryKey: keys.m("Comment").list(localParams),
    queryFn: async () => {
      const { listComments } = await import("../server/queries");
      return listComments(localParams, ctx);
    },
    ...options,
  });

  return {
    ...query,
    params: localParams,
    setParams: setLocalParams,
    nextPage: useCallback(() => {
      if (query.data && localParams.take) {
        const skip = (localParams.skip || 0) + localParams.take;
        if (skip < query.data.total) {
          setLocalParams((prev) => ({ ...prev, skip }));
        }
      }
    }, [query.data, localParams]),
    previousPage: useCallback(() => {
      if (localParams.skip && localParams.take) {
        const skip = Math.max(0, localParams.skip - localParams.take);
        setLocalParams((prev) => ({ ...prev, skip }));
      }
    }, [localParams]),
  };
}

export function useCreateComment(
  options?: UseMutationOptions<FlowComment, Error, FlowCommentCreate>,
) {
  const ctx = useFlowCtx();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: FlowCommentCreate) => {
      const { createComment } = await import("../server/actions");
      return createComment(data, ctx);
    },
    onSuccess: (data, variables, context) => {
      queryClient.invalidateQueries({ queryKey: [keys.m("Comment").tag()] });
      options?.onSuccess?.(data, variables, context);
    },
    ...options,
  });
}

export function useUpdateComment(
  id: string,
  options?: UseMutationOptions<FlowComment, Error, FlowCommentUpdate>,
) {
  const ctx = useFlowCtx();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: FlowCommentUpdate) => {
      const { updateComment } = await import("../server/actions");
      return updateComment(id, data, ctx);
    },
    onMutate: async (newData) => {
      // Optimistic update
      await queryClient.cancelQueries({
        queryKey: keys.m("Comment").byId(String(id)),
      });
      const previousData = queryClient.getQueryData(
        keys.m("Comment").byId(String(id)),
      );

      queryClient.setQueryData(
        keys.m("Comment").byId(String(id)),
        (old: any) => (old ? { ...old, ...newData } : old),
      );

      return { previousData };
    },
    onError: (err, newData, context: any) => {
      // Revert optimistic update on error
      if (context?.previousData) {
        queryClient.setQueryData(
          keys.m("Comment").byId(String(id)),
          context.previousData,
        );
      }
      options?.onError?.(err, newData, context);
    },
    onSettled: () => {
      queryClient.invalidateQueries({
        queryKey: keys.m("Comment").byId(String(id)),
      });
      queryClient.invalidateQueries({ queryKey: [keys.m("Comment").tag()] });
    },
    ...options,
  });
}

export function useDeleteComment(
  options?: UseMutationOptions<void, Error, string>,
) {
  const ctx = useFlowCtx();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { deleteComment } = await import("../server/actions");
      return deleteComment(id, ctx);
    },
    onSuccess: (data, id, context) => {
      queryClient.invalidateQueries({
        queryKey: keys.m("Comment").byId(String(id)),
      });
      queryClient.invalidateQueries({ queryKey: [keys.m("Comment").tag()] });
      options?.onSuccess?.(data, id, context);
    },
    ...options,
  });
}

export function useCommentMutation(options?: {
  mode: "create" | "update";
  id?: string;
  onSuccess?: (data: FlowComment) => void;
  onError?: (error: Error) => void;
}) {
  const { mode = "create", id, onSuccess, onError } = options || {};

  const createMutation = useCreateComment({
    onSuccess,
    onError,
  });

  const updateMutation = useUpdateComment(id!, {
    onSuccess,
    onError,
  });

  if (mode === "update" && id) {
    return updateMutation;
  }

  return createMutation as typeof createMutation;
}
