// @generated by next-prisma-flow-state-engine
// file: server/methods.ts

"use server";

import { prisma } from "../../prisma";
import type { Prisma } from "../../prisma";
import { FlowCtx, FlowPolicyError, deepMergePrismaData } from "../../core";
import { canUser } from "../../policies";
import { UserSelect } from "./selects";
import type { FlowUser } from "../types/schemas";

export async function findUnique(
  args: Prisma.UserFindUniqueArgs,
  ctx: FlowCtx = {},
): Promise<FlowUser | null> {
  const policy = await canUser("read", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.user.findUnique({
    select: UserSelect,
    ...args,
    where: { ...args.where, ...policy.where },
  }) as Promise<FlowUser | null>;
}

export async function findUniqueOrThrow(
  args: Prisma.UserFindUniqueOrThrowArgs,
  ctx: FlowCtx = {},
): Promise<FlowUser> {
  const policy = await canUser("read", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.user.findUniqueOrThrow({
    select: UserSelect,
    ...args,
    where: { ...args.where, ...policy.where },
  }) as Promise<FlowUser>;
}

export async function findFirst(
  args?: Prisma.UserFindFirstArgs,
  ctx: FlowCtx = {},
): Promise<FlowUser | null> {
  const policy = await canUser("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.user.findFirst({
    select: UserSelect,
    ...args,
    where: { ...args?.where, ...policy.where },
  }) as Promise<FlowUser | null>;
}

export async function findFirstOrThrow(
  args?: Prisma.UserFindFirstOrThrowArgs,
  ctx: FlowCtx = {},
): Promise<FlowUser> {
  const policy = await canUser("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.user.findFirstOrThrow({
    select: UserSelect,
    ...args,
    where: { ...args?.where, ...policy.where },
  }) as Promise<FlowUser>;
}

export async function findMany(
  args?: Prisma.UserFindManyArgs,
  ctx: FlowCtx = {},
): Promise<FlowUser[]> {
  const policy = await canUser("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.user.findMany({
    select: UserSelect,
    ...args,
    where: { ...args?.where, ...policy.where },
  }) as Promise<FlowUser[]>;
}

export async function create(
  args: Prisma.UserCreateArgs,
  ctx: FlowCtx = {},
): Promise<FlowUser> {
  const policy = await canUser("create", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const result = (await prisma.user.create({
    select: UserSelect,
    ...args,
    data: deepMergePrismaData(args.data, policy.data || {}, "User"),
  })) as FlowUser;

  return result;
}

export async function createMany(
  args: Prisma.UserCreateManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canUser("create", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  // Apply policy data to each item using deep merge
  const data = Array.isArray(args.data)
    ? args.data.map((item) =>
        deepMergePrismaData(item, policy.data || {}, "User"),
      )
    : deepMergePrismaData(args.data, policy.data || {});

  return prisma.user.createMany({
    ...args,
    data,
  });
}

export async function update(
  args: Prisma.UserUpdateArgs,
  ctx: FlowCtx = {},
): Promise<FlowUser> {
  const policy = await canUser("update", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const result = (await prisma.user.update({
    select: UserSelect,
    ...args,
    where: { ...args.where, ...policy.where },
    data: deepMergePrismaData(args.data, policy.data || {}, "User"),
  })) as FlowUser;

  return result;
}

export async function updateMany(
  args: Prisma.UserUpdateManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canUser("update", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.user.updateMany({
    ...args,
    where: { ...args.where, ...policy.where },
    data: deepMergePrismaData(args.data, policy.data || {}, "User"),
  });
}

export async function upsert(
  args: Prisma.UserUpsertArgs,
  ctx: FlowCtx = {},
): Promise<FlowUser> {
  // Check both create and update policies
  const createPolicy = await canUser("create", ctx);
  const updatePolicy = await canUser("update", ctx);

  // Need both permissions for upsert
  if (!createPolicy.ok || !updatePolicy.ok) {
    throw new FlowPolicyError("Insufficient permissions for upsert");
  }

  return prisma.user.upsert({
    select: UserSelect,
    ...args,
    where: { ...args.where, ...updatePolicy.where },
    create: deepMergePrismaData(args.create, createPolicy.data || {}, "User"),
    update: deepMergePrismaData(args.update, updatePolicy.data || {}, "User"),
  }) as Promise<FlowUser>;
}

export async function deleteOne(
  args: Prisma.UserDeleteArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canUser("delete", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.user.delete({
    ...args,
    where: { ...args.where, ...policy.where },
  });
}

export async function deleteMany(
  args?: Prisma.UserDeleteManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canUser("delete", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.user.deleteMany({
    ...args,
    where: { ...args?.where, ...policy.where },
  });
}

export async function count(args?: Prisma.UserCountArgs, ctx: FlowCtx = {}) {
  const policy = await canUser("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.user.count({
    ...args,
    where: { ...args?.where, ...policy.where },
  });
}

export async function aggregate(
  args: Prisma.UserAggregateArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canUser("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.user.aggregate({
    ...args,
    where: { ...args.where, ...policy.where },
  });
}

export async function groupBy<
  T extends Prisma.UserGroupByArgs,
  HasSelectOrTake extends Prisma.Or<
    Prisma.Extends<"skip", Prisma.Keys<T>>,
    Prisma.Extends<"take", Prisma.Keys<T>>
  >,
  OrderByArg extends Prisma.True extends HasSelectOrTake
    ? { orderBy: Prisma.UserGroupByArgs["orderBy"] }
    : { orderBy?: Prisma.UserGroupByArgs["orderBy"] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<
    Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
  >,
  ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<T["having"]>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [
                  Error,
                  "Field ",
                  P,
                  ` used in "having" needs to be provided in "by"`,
                ];
        }[HavingFields]
      : "take" extends Prisma.Keys<T>
        ? "orderBy" extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : "skip" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
>(
  args: Prisma.SubsetIntersection<T, Prisma.UserGroupByArgs, OrderByArg> &
    InputErrors,
  ctx: FlowCtx = {},
): Promise<
  {} extends InputErrors ? Prisma.GetUserGroupByPayload<T> : InputErrors
> {
  const policy = await canUser("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.user.groupBy({
    ...(args as any),
    where: { ...args.where, ...policy.where },
  } as any) as any;
}
