// @generated by next-prisma-flow-state-engine
// file: server/selects.ts

import "server-only";
import { Prisma } from "../../prisma";

// Scalar selects
export const UserScalarSelect = {
  id: true,
  email: true,
  name: true,
  avatar: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.UserSelect;
export const UserListScalarSelect = {
  id: true,
  name: true,
  description: true,
  color: true,
  icon: true,
  orderIndex: true,
  isDefault: true,
  createdAt: true,
  updatedAt: true,
  userId: true,
} as Prisma.ListSelect;
export const UserTodoScalarSelect = {
  id: true,
  title: true,
  description: true,
  status: true,
  priority: true,
  dueDate: true,
  completedAt: true,
  orderIndex: true,
  isArchived: true,
  createdAt: true,
  updatedAt: true,
  listId: true,
  userId: true,
  parentId: true,
} as Prisma.TodoSelect;
export const UserTagScalarSelect = {
  id: true,
  name: true,
  color: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.TagSelect;

// Nested relation selects
export const UserListsTodosTagsSelect = {
  ...UserTagScalarSelect,
  todos: false,
} as Prisma.TagSelect;
export const UserListsTodosSubtasksTagsSelect = {
  ...UserTagScalarSelect,
  todos: false,
} as Prisma.TagSelect;
export const UserListsTodosSubtasksSelect = {
  ...UserTodoScalarSelect,
  list: false,
  tags: {
    select: UserListsTodosSubtasksTagsSelect,
    take: 50,
  },
  subtasks: false,
  parent: false,
  user: false,
} as Prisma.TodoSelect;
export const UserListsTodosParentTagsSelect = {
  ...UserTagScalarSelect,
  todos: false,
} as Prisma.TagSelect;
export const UserListsTodosParentSelect = {
  ...UserTodoScalarSelect,
  list: false,
  tags: {
    select: UserListsTodosParentTagsSelect,
    take: 50,
  },
  subtasks: false,
  parent: false,
  user: false,
} as Prisma.TodoSelect;
export const UserListsTodosSelect = {
  ...UserTodoScalarSelect,
  list: false,
  tags: {
    select: UserListsTodosTagsSelect,
    take: 50,
  },
  subtasks: {
    select: UserListsTodosSubtasksSelect,
    take: 50,
  },
  parent: { select: UserListsTodosParentSelect },
  user: false,
} as Prisma.TodoSelect;
export const UserListsSelect = {
  ...UserListScalarSelect,
  todos: {
    select: UserListsTodosSelect,
    take: 50,
  },
  user: false,
} as Prisma.ListSelect;
export const UserTodosListSelect = {
  ...UserListScalarSelect,
  todos: false,
  user: false,
} as Prisma.ListSelect;
export const UserTodosTagsSelect = {
  ...UserTagScalarSelect,
  todos: false,
} as Prisma.TagSelect;
export const UserTodosSubtasksListSelect = {
  ...UserListScalarSelect,
  todos: false,
  user: false,
} as Prisma.ListSelect;
export const UserTodosSubtasksTagsSelect = {
  ...UserTagScalarSelect,
  todos: false,
} as Prisma.TagSelect;
export const UserTodosSubtasksSelect = {
  ...UserTodoScalarSelect,
  list: { select: UserTodosSubtasksListSelect },
  tags: {
    select: UserTodosSubtasksTagsSelect,
    take: 50,
  },
  subtasks: false,
  parent: false,
  user: false,
} as Prisma.TodoSelect;
export const UserTodosParentListSelect = {
  ...UserListScalarSelect,
  todos: false,
  user: false,
} as Prisma.ListSelect;
export const UserTodosParentTagsSelect = {
  ...UserTagScalarSelect,
  todos: false,
} as Prisma.TagSelect;
export const UserTodosParentSelect = {
  ...UserTodoScalarSelect,
  list: { select: UserTodosParentListSelect },
  tags: {
    select: UserTodosParentTagsSelect,
    take: 50,
  },
  subtasks: false,
  parent: false,
  user: false,
} as Prisma.TodoSelect;
export const UserTodosSelect = {
  ...UserTodoScalarSelect,
  list: { select: UserTodosListSelect },
  tags: {
    select: UserTodosTagsSelect,
    take: 50,
  },
  subtasks: {
    select: UserTodosSubtasksSelect,
    take: 50,
  },
  parent: { select: UserTodosParentSelect },
  user: false,
} as Prisma.TodoSelect;

// Main select
export const UserSelect = {
  ...UserScalarSelect,
  lists: {
    take: 50,
    select: UserListsSelect,
  },
  todos: {
    take: 50,
    select: UserTodosSelect,
  },
} as Prisma.UserSelect;
