// @generated by next-prisma-flow-state-engine
// file: index.ts

// Tree-shakeable named exports
export * as TodoServer from "./server";
export * as TodoClient from "./client";
export * as TodoTypes from "./types";

// Direct exports for common usage
export {
  // Hooks
  useTodo,
  useTodoList,
  useCreateTodo,
  useUpdateTodo,
  useDeleteTodo,
  useTodoMutation,
} from "./client/hooks";

export {
  // Forms
  useTodoForm,
  useTodoQuickForm,
  type TodoFormOptions,
  type TodoFormProps,
} from "./client/forms";

export {
  // Schemas
  TodoCreateSchema,
  TodoUpdateSchema,
  TodoFilterSchema,
  type FlowTodo,
  type FlowTodoCreate,
  type FlowTodoUpdate,
  type FlowTodoFilter,
} from "./types/schemas";

export {
  // Types
  type TodoWithRelations,
  type TodoListItem,
  type TodoPage,
  type TodoCursor,
} from "./types/types";

// Server-only exports (for server components/actions)
export type { TodoListParams } from "./server/queries";
