// @generated by next-prisma-flow-state-engine
// file: client/forms.ts

"use client";

import { useCallback, useEffect, useState, useRef } from "react";
import {
  useForm,
  type UseFormReturn,
  type UseFormProps,
  type Path,
  type PathValue,
  type FieldErrors,
} from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { PostCreateSchema, PostUpdateSchema } from "../types/schemas";
import type {
  FlowPost,
  FlowPostCreate,
  FlowPostUpdate,
} from "../types/schemas";
import { usePost, useCreatePost, useUpdatePost } from "./hooks";
import {
  usePostFormAutosave,
  usePostFormFieldTracking,
  usePostFormHistory,
} from "./composables";

export type PostFieldState = {
  isDirty: boolean;
  isTouched: boolean;
  error?: any;
  current: any;
  original?: any;
  hasChanged?: boolean;
};

export type PostDirtyField = {
  field: string;
  original?: any;
  current: any;
};

export type PostAutosaveConfig = {
  enabled: boolean;
  debounceMs?: number;
  fields?: string[];
  onFieldSave?: (field: string, value: any) => void;
  onFieldError?: (field: string, error: Error) => void;
};

export type PostFormFeatures = {
  autosave?: PostAutosaveConfig | boolean;
  tracking?: boolean;
  history?:
    | {
        enabled: boolean;
        maxHistorySize?: number;
      }
    | boolean;
};

// Create form options
export type PostCreateFormOptions = {
  defaultValues?: Partial<FlowPostCreate>;
  onSuccess?: (data: FlowPost) => void;
  onError?: (error: Error) => void;
  formOptions?: Omit<
    UseFormProps<FlowPostCreate>,
    "resolver" | "defaultValues"
  >;
  features?: PostFormFeatures;
};

export type PostUpdateFormOptions = {
  defaultValues?: Partial<FlowPostUpdate>;
  onSuccess?: (data: FlowPost) => void;
  onError?: (error: Error) => void;
  formOptions?: Omit<
    UseFormProps<FlowPostUpdate>,
    "resolver" | "defaultValues"
  >;
  features?: PostFormFeatures;
};

function extractScalarFields(data: any): any {
  const result: any = {};
  Object.keys(data).forEach((key) => {
    const value = data[key];
    if (
      value === null ||
      (typeof value !== "object" && !Array.isArray(value))
    ) {
      result[key] = value;
    }
  });
  return result;
}

export function useCreatePostForm(options?: PostCreateFormOptions) {
  const { defaultValues, onSuccess, onError, formOptions, features } =
    options || {};

  const form = useForm<FlowPostCreate>({
    ...formOptions,
    resolver: zodResolver(PostCreateSchema),
    defaultValues: defaultValues as FlowPostCreate,
  });

  const mutation = useCreatePost({
    onSuccess: (data) => {
      form.reset();
      onSuccess?.(data);
    },
    onError,
  });

  // Field operations
  const getFieldState = useCallback(
    (name: Path<FlowPostCreate>): PostFieldState => {
      const fieldState = form.getFieldState(name);
      return {
        isDirty: fieldState.isDirty,
        isTouched: fieldState.isTouched,
        error: fieldState.error,
        current: form.getValues(name),
        original: (form.formState.defaultValues as any)?.[name],
      };
    },
    [form],
  );

  const resetField = useCallback(
    (name: Path<FlowPostCreate>) => {
      form.resetField(name);
    },
    [form],
  );

  const setFieldValue = useCallback(
    <T extends Path<FlowPostCreate>>(
      name: T,
      value: PathValue<FlowPostCreate, T>,
      options?: {
        shouldValidate?: boolean;
        shouldDirty?: boolean;
        shouldTouch?: boolean;
      },
    ) => {
      form.setValue(name, value, options);
    },
    [form],
  );

  const validateField = useCallback(
    (name: Path<FlowPostCreate>) => {
      return form.trigger(name);
    },
    [form],
  );

  const clearFieldError = useCallback(
    (name: Path<FlowPostCreate>) => {
      form.clearErrors(name);
    },
    [form],
  );

  const batchUpdate = useCallback(
    (updates: Partial<FlowPostCreate>) => {
      Object.entries(updates).forEach(([key, value]) => {
        form.setValue(key as Path<FlowPostCreate>, value as any);
      });
    },
    [form],
  );

  const getDirtyFields = useCallback((): PostDirtyField[] => {
    const dirtyFields: PostDirtyField[] = [];
    Object.keys(form.formState.dirtyFields).forEach((key) => {
      if ((form.formState.dirtyFields as any)[key]) {
        dirtyFields.push({
          field: key,
          original: (form.formState.defaultValues as any)?.[key],
          current: form.getValues(key as Path<FlowPostCreate>),
        });
      }
    });
    return dirtyFields;
  }, [form]);

  // Submit handler
  const submit = useCallback(
    (data: FlowPostCreate) => {
      console.log("[PostCreateForm] Submitting:", data);
      return mutation.mutate(data);
    },
    [mutation],
  );

  const onInvalid = useCallback((errors: any) => {
    console.error("[PostCreateForm] Validation failed:", errors);
  }, []);

  // Always call composables (no conditional hooks)
  const autosaveConfig =
    typeof features?.autosave === "object"
      ? features.autosave
      : { enabled: !!features?.autosave };
  const autosave = usePostFormAutosave(form, mutation, autosaveConfig);

  const tracking = usePostFormFieldTracking(form);

  const historyConfig =
    typeof features?.history === "object"
      ? features.history
      : { enabled: !!features?.history };
  const history = usePostFormHistory(form, historyConfig);

  return {
    form,
    mutation,
    submit: form.handleSubmit(submit, onInvalid),
    isSubmitting: mutation.isPending,
    error: mutation.error,
    isSuccess: mutation.isSuccess,
    reset: () => form.reset(),
    // Field operations
    getFieldState,
    resetField,
    setFieldValue,
    validateField,
    clearFieldError,
    batchUpdate,
    getDirtyFields,
    // Include features if enabled
    ...(autosaveConfig.enabled ? { autosave } : {}),
    ...(features?.tracking ? { tracking } : {}),
    ...(historyConfig.enabled ? { history } : {}),
  };
}

export function useUpdatePostForm(id: string, options?: PostUpdateFormOptions) {
  const { defaultValues, onSuccess, onError, formOptions, features } =
    options || {};

  const originalRef = useRef<FlowPost>();

  // Fetch existing data
  const { data: existingData } = usePost(id);

  // Initialize form
  const form = useForm<FlowPostUpdate>({
    ...formOptions,
    resolver: zodResolver(PostUpdateSchema),
    defaultValues: defaultValues as FlowPostUpdate,
  });

  // Track autosave ref to use in useEffect
  const autosaveRef = useRef<ReturnType<typeof usePostFormAutosave>>();

  // Update form when existing data loads
  useEffect(() => {
    if (existingData) {
      originalRef.current = existingData;
      const scalarData = extractScalarFields(existingData);
      console.log("[PostUpdateForm] Loading data:", scalarData);

      // Pause autosave during form reset to prevent loops
      if (autosaveRef.current?.pauseAutosave) {
        autosaveRef.current.pauseAutosave(() => {
          form.reset(scalarData as FlowPostUpdate, {
            keepDirtyValues: true,
            keepErrors: true,
          });
        });
      } else {
        form.reset(scalarData as FlowPostUpdate, {
          keepDirtyValues: true,
          keepErrors: true,
        });
      }
    }
  }, [existingData, form]);

  // Update mutation
  const mutation = useUpdatePost(id, {
    onSuccess,
    onError,
  });

  // Field operations with original comparison
  const getFieldState = useCallback(
    (name: Path<FlowPostUpdate>): PostFieldState => {
      const fieldState = form.getFieldState(name);
      const currentValue = form.getValues(name);
      const originalValue = originalRef.current?.[name as keyof FlowPost];
      return {
        isDirty: fieldState.isDirty,
        isTouched: fieldState.isTouched,
        error: fieldState.error,
        current: currentValue,
        original: originalValue,
        hasChanged: currentValue !== originalValue,
      };
    },
    [form],
  );

  const resetField = useCallback(
    (name: Path<FlowPostUpdate>) => {
      const originalValue = originalRef.current?.[name as keyof FlowPost];
      form.setValue(name, originalValue as any);
      form.clearErrors(name);
    },
    [form],
  );

  const setFieldValue = useCallback(
    <T extends Path<FlowPostUpdate>>(
      name: T,
      value: PathValue<FlowPostUpdate, T>,
      options?: {
        shouldValidate?: boolean;
        shouldDirty?: boolean;
        shouldTouch?: boolean;
      },
    ) => {
      form.setValue(name, value, options);
    },
    [form],
  );

  const validateField = useCallback(
    (name: Path<FlowPostUpdate>) => {
      return form.trigger(name);
    },
    [form],
  );

  const clearFieldError = useCallback(
    (name: Path<FlowPostUpdate>) => {
      form.clearErrors(name);
    },
    [form],
  );

  const batchUpdate = useCallback(
    (updates: Partial<FlowPostUpdate>) => {
      Object.entries(updates).forEach(([key, value]) => {
        form.setValue(key as Path<FlowPostUpdate>, value as any);
      });
    },
    [form],
  );

  const getDirtyFields = useCallback((): PostDirtyField[] => {
    const dirtyFields: PostDirtyField[] = [];
    Object.keys(form.formState.dirtyFields).forEach((key) => {
      if ((form.formState.dirtyFields as any)[key]) {
        dirtyFields.push({
          field: key,
          original: originalRef.current?.[key as keyof FlowPost],
          current: form.getValues(key as Path<FlowPostUpdate>),
        });
      }
    });
    return dirtyFields;
  }, [form]);

  // Submit handler
  const submit = useCallback(
    (data: FlowPostUpdate) => {
      console.log("[PostUpdateForm] Submitting:", data);
      return mutation.mutate(data);
    },
    [mutation],
  );

  const onInvalid = useCallback((errors: any) => {
    console.error("[PostUpdateForm] Validation failed:", errors);
  }, []);

  // Always call composables (no conditional hooks)
  const autosaveConfig =
    typeof features?.autosave === "object"
      ? features.autosave
      : { enabled: !!features?.autosave };
  const autosave = usePostFormAutosave(form, mutation, autosaveConfig);

  // Store autosave ref for use in useEffect
  useEffect(() => {
    autosaveRef.current = autosave;
  }, [autosave]);

  const tracking = usePostFormFieldTracking(form, originalRef.current);

  const historyConfig =
    typeof features?.history === "object"
      ? features.history
      : { enabled: !!features?.history };
  const history = usePostFormHistory(form, historyConfig);

  return {
    form,
    mutation,
    original: originalRef.current,
    submit: form.handleSubmit(submit, onInvalid),
    isSubmitting: mutation.isPending,
    error: mutation.error,
    isSuccess: mutation.isSuccess,
    reset: () => form.reset(extractScalarFields(originalRef.current || {})),
    // Field operations
    getFieldState,
    resetField,
    setFieldValue,
    validateField,
    clearFieldError,
    batchUpdate,
    getDirtyFields,
    // Include features if enabled
    ...(autosaveConfig.enabled ? { autosave } : {}),
    ...(features?.tracking ? { tracking } : {}),
    ...(historyConfig.enabled ? { history } : {}),
  };
}

export type PostCreateFormProps = {
  form: UseFormReturn<FlowPostCreate>;
  onSubmit: () => void;
  isSubmitting: boolean;
  error?: Error | null;
};

export type PostUpdateFormProps = {
  form: UseFormReturn<FlowPostUpdate>;
  onSubmit: () => void;
  isSubmitting: boolean;
  error?: Error | null;
  original?: FlowPost;
};
