// @generated by next-prisma-flow-state-engine
// file: types/schemas.ts

import { z } from "zod";

// Scalar fields only
export const CommentScalarSchema = z.object({
  id: z.string(),
  content: z.string(),
  postId: z.string(),
  authorId: z.string(),
  createdAt: z.date(),
  updatedAt: z.date(),
});

// Relation schemas
export const CommentAuthorPostsSchema = z.object({
  id: z.string(),
  title: z.string(),
  content: z.string().optional().nullable(),
  createdAt: z.date(),
});

export const CommentPostAuthorSchema = z.object({
  id: z.string(),
  email: z.string(),
  name: z.string().optional().nullable(),
});

export const CommentAuthorSchema = z.object({
  id: z.string(),
  email: z.string(),
  name: z.string().optional().nullable(),
  posts: z.array(CommentAuthorPostsSchema).optional(),
});

export const CommentPostSchema = z.object({
  id: z.string(),
  title: z.string(),
  content: z.string().optional().nullable(),
  createdAt: z.date(),
  author: CommentPostAuthorSchema.optional(),
});

// Main schema with relations
export const CommentSchema = CommentScalarSchema.extend({
  author: CommentAuthorSchema.optional(),
  post: CommentPostSchema.optional(),
});

// Input schemas for create operations
const CommentCreateAuthorInputSchema = z.object({
  id: z.string().optional(),
  email: z.string(),
  name: z.string().optional().nullable(),
  posts: z
    .object({
      connect: z
        .union([
          z.object({ id: z.string() }),
          z.array(z.object({ id: z.string() })),
        ])
        .optional(),
    })
    .optional(),
  comments: z
    .object({
      connect: z
        .union([
          z.object({ id: z.string() }),
          z.array(z.object({ id: z.string() })),
        ])
        .optional(),
    })
    .optional(),
});

const CommentCreatePostInputSchema = z.object({
  id: z.string().optional(),
  title: z.string(),
  content: z.string().optional().nullable(),
  createdAt: z.date().optional(),
  author: z
    .object({
      connect: z.object({ id: z.string() }).optional(),
    })
    .optional(),
  comments: z
    .object({
      connect: z
        .union([
          z.object({ id: z.string() }),
          z.array(z.object({ id: z.string() })),
        ])
        .optional(),
    })
    .optional(),
});

export const CommentCreateSchema = z.object({
  id: z.string().optional(),
  content: z.string(),
  createdAt: z.date().optional(),
  postId: z.string(),
  authorId: z.string(),
  post: z
    .object({
      create: CommentCreatePostInputSchema.optional(),
      connect: z.object({ id: z.string() }).optional(),
      connectOrCreate: z
        .object({
          where: z.object({ id: z.string() }),
          create: CommentCreatePostInputSchema,
        })
        .optional(),
    })
    .optional(),
  author: z
    .object({
      create: CommentCreateAuthorInputSchema.optional(),
      connect: z.object({ id: z.string() }).optional(),
      connectOrCreate: z
        .object({
          where: z.object({ id: z.string() }),
          create: CommentCreateAuthorInputSchema,
        })
        .optional(),
    })
    .optional(),
});

export const CommentCreateManyInputSchema = z.object({
  id: z.string().optional(),
  content: z.string(),
  createdAt: z.date().optional(),
});

// Input schemas for update operations
const CommentUpdateAuthorInputSchema = z.object({
  email: z.string().optional(),
  name: z.string().optional().nullable(),
  posts: z
    .object({
      connect: z
        .union([
          z.object({ id: z.string() }),
          z.array(z.object({ id: z.string() })),
        ])
        .optional(),
      disconnect: z
        .union([
          z.object({ id: z.string() }),
          z.array(z.object({ id: z.string() })),
        ])
        .optional(),
      set: z
        .union([
          z.object({ id: z.string() }),
          z.array(z.object({ id: z.string() })),
        ])
        .optional(),
    })
    .optional(),
  comments: z
    .object({
      connect: z
        .union([
          z.object({ id: z.string() }),
          z.array(z.object({ id: z.string() })),
        ])
        .optional(),
      disconnect: z
        .union([
          z.object({ id: z.string() }),
          z.array(z.object({ id: z.string() })),
        ])
        .optional(),
      set: z
        .union([
          z.object({ id: z.string() }),
          z.array(z.object({ id: z.string() })),
        ])
        .optional(),
    })
    .optional(),
});

const CommentUpdatePostInputSchema = z.object({
  title: z.string().optional(),
  content: z.string().optional().nullable(),
  createdAt: z.date().optional(),
  author: z
    .object({
      connect: z.object({ id: z.string() }).optional(),
    })
    .optional(),
  comments: z
    .object({
      connect: z
        .union([
          z.object({ id: z.string() }),
          z.array(z.object({ id: z.string() })),
        ])
        .optional(),
      disconnect: z
        .union([
          z.object({ id: z.string() }),
          z.array(z.object({ id: z.string() })),
        ])
        .optional(),
      set: z
        .union([
          z.object({ id: z.string() }),
          z.array(z.object({ id: z.string() })),
        ])
        .optional(),
    })
    .optional(),
});

export const CommentUpdateSchema = z.object({
  content: z.string().optional(),
  createdAt: z.date().optional(),
  postId: z.string().optional(),
  authorId: z.string().optional(),
  post: z
    .object({
      create: CommentCreatePostInputSchema.optional(),
      connect: z.object({ id: z.string() }).optional(),
      connectOrCreate: z
        .object({
          where: z.object({ id: z.string() }),
          create: CommentCreatePostInputSchema,
        })
        .optional(),
      update: z
        .object({
          where: z.object({ id: z.string() }).optional(),
          data: CommentUpdatePostInputSchema,
        })
        .optional(),
      upsert: z
        .object({
          where: z.object({ id: z.string() }),
          update: CommentUpdatePostInputSchema,
          create: CommentCreatePostInputSchema,
        })
        .optional(),
    })
    .optional(),
  author: z
    .object({
      create: CommentCreateAuthorInputSchema.optional(),
      connect: z.object({ id: z.string() }).optional(),
      connectOrCreate: z
        .object({
          where: z.object({ id: z.string() }),
          create: CommentCreateAuthorInputSchema,
        })
        .optional(),
      update: z
        .object({
          where: z.object({ id: z.string() }).optional(),
          data: CommentUpdateAuthorInputSchema,
        })
        .optional(),
      upsert: z
        .object({
          where: z.object({ id: z.string() }),
          update: CommentUpdateAuthorInputSchema,
          create: CommentCreateAuthorInputSchema,
        })
        .optional(),
    })
    .optional(),
});

export const CommentUpdateManyInputSchema = z.object({
  content: z.string().optional().nullable(),
  createdAt: z.date().optional().nullable(),
});

export const CommentUpsertInputSchema = z.object({
  create: CommentCreateSchema,
  update: CommentUpdateSchema,
});

// Filter and where schemas
// Relation where schemas
export const CommentPostFilterSchema = z.object({
  id: z
    .union([
      z.string(),
      z.object({
        equals: z.string().optional(),
        contains: z.string().optional(),
        startsWith: z.string().optional(),
        endsWith: z.string().optional(),
        in: z.array(z.string()).optional(),
        notIn: z.array(z.string()).optional(),
        not: z.string().optional(),
      }),
    ])
    .optional(),
  title: z
    .union([
      z.string(),
      z.object({
        equals: z.string().optional(),
        contains: z.string().optional(),
        startsWith: z.string().optional(),
        endsWith: z.string().optional(),
        in: z.array(z.string()).optional(),
        notIn: z.array(z.string()).optional(),
        not: z.string().optional(),
      }),
    ])
    .optional(),
  content: z
    .union([
      z.string().optional().nullable(),
      z.object({
        equals: z.string().optional(),
        contains: z.string().optional(),
        startsWith: z.string().optional(),
        endsWith: z.string().optional(),
        in: z.array(z.string()).optional(),
        notIn: z.array(z.string()).optional(),
        not: z.string().optional(),
      }),
    ])
    .optional(),
  createdAt: z
    .union([
      z.date(),
      z.object({
        equals: z.date().optional(),
        lt: z.date().optional(),
        lte: z.date().optional(),
        gt: z.date().optional(),
        gte: z.date().optional(),
        in: z.array(z.date()).optional(),
        notIn: z.array(z.date()).optional(),
        not: z.date().optional(),
      }),
    ])
    .optional(),
  AND: z.array(z.any()).optional(),
  OR: z.array(z.any()).optional(),
  NOT: z.any().optional(),
});

export const CommentAuthorFilterSchema = z.object({
  id: z
    .union([
      z.string(),
      z.object({
        equals: z.string().optional(),
        contains: z.string().optional(),
        startsWith: z.string().optional(),
        endsWith: z.string().optional(),
        in: z.array(z.string()).optional(),
        notIn: z.array(z.string()).optional(),
        not: z.string().optional(),
      }),
    ])
    .optional(),
  email: z
    .union([
      z.string(),
      z.object({
        equals: z.string().optional(),
        contains: z.string().optional(),
        startsWith: z.string().optional(),
        endsWith: z.string().optional(),
        in: z.array(z.string()).optional(),
        notIn: z.array(z.string()).optional(),
        not: z.string().optional(),
      }),
    ])
    .optional(),
  name: z
    .union([
      z.string().optional().nullable(),
      z.object({
        equals: z.string().optional(),
        contains: z.string().optional(),
        startsWith: z.string().optional(),
        endsWith: z.string().optional(),
        in: z.array(z.string()).optional(),
        notIn: z.array(z.string()).optional(),
        not: z.string().optional(),
      }),
    ])
    .optional(),
  AND: z.array(z.any()).optional(),
  OR: z.array(z.any()).optional(),
  NOT: z.any().optional(),
});

// Base filter schema
export const CommentFilterBaseSchema = z.object({
  id: z
    .union([
      z.string(),
      z.object({
        equals: z.string().optional(),
        contains: z.string().optional(),
        startsWith: z.string().optional(),
        endsWith: z.string().optional(),
        in: z.array(z.string()).optional(),
        notIn: z.array(z.string()).optional(),
        not: z.string().optional(),
      }),
    ])
    .optional(),
  content: z
    .union([
      z.string(),
      z.object({
        equals: z.string().optional(),
        contains: z.string().optional(),
        startsWith: z.string().optional(),
        endsWith: z.string().optional(),
        in: z.array(z.string()).optional(),
        notIn: z.array(z.string()).optional(),
        not: z.string().optional(),
      }),
    ])
    .optional(),
  createdAt: z
    .union([
      z.date(),
      z.object({
        equals: z.date().optional(),
        lt: z.date().optional(),
        lte: z.date().optional(),
        gt: z.date().optional(),
        gte: z.date().optional(),
        in: z.array(z.date()).optional(),
        notIn: z.array(z.date()).optional(),
        not: z.date().optional(),
      }),
    ])
    .optional(),
  post: z.union([CommentPostFilterSchema, z.null()]).optional(),
  author: z.union([CommentAuthorFilterSchema, z.null()]).optional(),
  AND: z.union([z.any(), z.array(z.any())]).optional(),
  OR: z.array(z.any()).optional(),
  NOT: z.union([z.any(), z.array(z.any())]).optional(),
});

// Extended filter schema with self-references
export const CommentFilterSchema = CommentFilterBaseSchema.extend({
  AND: z.array(CommentFilterBaseSchema).optional(),
  OR: z.array(CommentFilterBaseSchema).optional(),
  NOT: CommentFilterBaseSchema.optional(),
});

// Alias for Prisma compatibility
export const CommentWhereInputSchema = CommentFilterSchema;

export const CommentWhereUniqueInputSchema = z.object({
  id: z.string().optional(),
});

// Type exports
export type FlowComment = z.infer<typeof CommentSchema>;
export type FlowCommentCreate = z.infer<typeof CommentCreateSchema>;
export type FlowCommentUpdate = z.infer<typeof CommentUpdateSchema>;
export type FlowCommentFilter = z.infer<typeof CommentFilterSchema>;
export type FlowCommentWhere = z.infer<typeof CommentWhereInputSchema>;
export type FlowCommentWhereUnique = z.infer<
  typeof CommentWhereUniqueInputSchema
>;
