// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-13T11:48:22.080Z

import { authors } from "./author";
import { categories } from "./category";
import { posts } from "./post";
import { comments } from "./comment";

import type { ModelType as Author } from "./author/types";
import type { ModelType as Category } from "./category/types";
import type { ModelType as Post } from "./post/types";
import type { ModelType as Comment } from "./comment/types";

// Export all models
export { authors, categories, posts, comments };

// Export all types
export type { Author, Category, Post, Comment };

// Export shared utilities
export { prisma } from "./prisma";
export * as zod from "./zod";
