// @generated by next-prisma-flow-state-engine
// file: client/hooks.ts

"use client";

import {
  useQuery,
  useMutation,
  useQueryClient,
  UseQueryOptions,
  UseMutationOptions,
} from "@tanstack/react-query";
import { useState, useCallback } from "react";
import { keys } from "../../core/keys";
import { useFlowCtx } from "../../core/provider";
import type { TagListParams } from "../server/queries";
import type { FlowTag, FlowTagCreate, FlowTagUpdate } from "../types/schemas";

export function useTag(
  id: string,
  options?: Omit<UseQueryOptions<FlowTag | null>, "queryKey" | "queryFn">,
) {
  const ctx = useFlowCtx();

  return useQuery({
    queryKey: keys.m("Tag").byId(String(id)),
    queryFn: async () => {
      const { getTagById } = await import("../server/queries");
      return getTagById(id, ctx);
    },
    ...options,
  });
}

export function useTagList(
  params?: TagListParams,
  options?: Omit<
    UseQueryOptions<{ items: FlowTag[]; total: number }>,
    "queryKey" | "queryFn"
  >,
) {
  const ctx = useFlowCtx();
  const [localParams, setLocalParams] = useState(params || {});

  const query = useQuery({
    queryKey: keys.m("Tag").list(localParams),
    queryFn: async () => {
      const { listTags } = await import("../server/queries");
      return listTags(localParams, ctx);
    },
    ...options,
  });

  return {
    ...query,
    params: localParams,
    setParams: setLocalParams,
    nextPage: useCallback(() => {
      if (query.data && localParams.take) {
        const skip = (localParams.skip || 0) + localParams.take;
        if (skip < query.data.total) {
          setLocalParams((prev) => ({ ...prev, skip }));
        }
      }
    }, [query.data, localParams]),
    previousPage: useCallback(() => {
      if (localParams.skip && localParams.take) {
        const skip = Math.max(0, localParams.skip - localParams.take);
        setLocalParams((prev) => ({ ...prev, skip }));
      }
    }, [localParams]),
  };
}

export function useCreateTag(
  options?: UseMutationOptions<FlowTag, Error, FlowTagCreate>,
) {
  const ctx = useFlowCtx();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: FlowTagCreate) => {
      const { createTag } = await import("../server/actions");
      return createTag(data, ctx);
    },
    onSuccess: (data, variables, context) => {
      queryClient.invalidateQueries({ queryKey: [keys.m("Tag").tag()] });
      options?.onSuccess?.(data, variables, context);
    },
    ...options,
  });
}

export function useUpdateTag(
  id: string,
  options?: UseMutationOptions<FlowTag, Error, FlowTagUpdate>,
) {
  const ctx = useFlowCtx();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: FlowTagUpdate) => {
      const { updateTag } = await import("../server/actions");
      return updateTag(id, data, ctx);
    },
    onMutate: async (newData) => {
      // Optimistic update
      await queryClient.cancelQueries({
        queryKey: keys.m("Tag").byId(String(id)),
      });
      const previousData = queryClient.getQueryData(
        keys.m("Tag").byId(String(id)),
      );

      queryClient.setQueryData(keys.m("Tag").byId(String(id)), (old: any) =>
        old ? { ...old, ...newData } : old,
      );

      return { previousData };
    },
    onError: (err, newData, context: any) => {
      // Revert optimistic update on error
      if (context?.previousData) {
        queryClient.setQueryData(
          keys.m("Tag").byId(String(id)),
          context.previousData,
        );
      }
      options?.onError?.(err, newData, context);
    },
    onSettled: () => {
      queryClient.invalidateQueries({
        queryKey: keys.m("Tag").byId(String(id)),
      });
      queryClient.invalidateQueries({ queryKey: [keys.m("Tag").tag()] });
    },
    ...options,
  });
}

export function useDeleteTag(
  options?: UseMutationOptions<void, Error, string>,
) {
  const ctx = useFlowCtx();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { deleteTag } = await import("../server/actions");
      return deleteTag(id, ctx);
    },
    onSuccess: (data, id, context) => {
      queryClient.invalidateQueries({
        queryKey: keys.m("Tag").byId(String(id)),
      });
      queryClient.invalidateQueries({ queryKey: [keys.m("Tag").tag()] });
      options?.onSuccess?.(data, id, context);
    },
    ...options,
  });
}

export function useTagMutation(options?: {
  mode: "create" | "update";
  id?: string;
  onSuccess?: (data: FlowTag) => void;
  onError?: (error: Error) => void;
}) {
  const { mode = "create", id, onSuccess, onError } = options || {};

  const createMutation = useCreateTag({
    onSuccess,
    onError,
  });

  const updateMutation = useUpdateTag(id!, {
    onSuccess,
    onError,
  });

  if (mode === "update" && id) {
    return updateMutation;
  }

  return createMutation as typeof createMutation;
}
