// @generated by next-prisma-flow-state-engine
// file: index.ts

// Tree-shakeable named exports
export * as UserServer from "./server";
export * as UserClient from "./client";
export * as UserTypes from "./types";

// Direct exports for common usage
export {
  // Hooks
  useUser,
  useUserList,
  useCreateUser,
  useUpdateUser,
  useDeleteUser,
  useUserMutation,
} from "./client/hooks";

export {
  // Forms
  useUserForm,
  useUserQuickForm,
  type UserFormOptions,
  type UserFormProps,
} from "./client/forms";

export {
  // Schemas
  UserCreateSchema,
  UserUpdateSchema,
  UserFilterSchema,
  type FlowUser,
  type FlowUserCreate,
  type FlowUserUpdate,
  type FlowUserFilter,
} from "./types/schemas";

export {
  // Types
  type UserWithRelations,
  type UserListItem,
  type UserPage,
  type UserCursor,
} from "./types/types";

// Server-only exports (for server components/actions)
export type { UserListParams } from "./server/queries";
