// @generated by next-prisma-flow-state-engine
// file: server/selects.ts

import "server-only";
import { Prisma } from "../../prisma";

// Scalar selects
export const AuthorScalarSelect = {
  id: true,
  email: true,
  name: true,
  bio: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.AuthorSelect;
export const AuthorPostScalarSelect = {
  id: true,
  title: true,
  slug: true,
  excerpt: true,
  content: true,
  published: true,
  publishedAt: true,
  createdAt: true,
  updatedAt: true,
  authorId: true,
} as Prisma.PostSelect;
export const AuthorTagScalarSelect = {
  id: true,
  name: true,
  slug: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.TagSelect;

// Nested relation selects
export const AuthorPostsTagsSelect = {
  ...AuthorTagScalarSelect,
  posts: false,
} as Prisma.TagSelect;
export const AuthorPostsSelect = {
  ...AuthorPostScalarSelect,
  author: false,
  tags: {
    select: AuthorPostsTagsSelect,
    take: 50,
  },
} as Prisma.PostSelect;

// Main select
export const AuthorSelect = {
  ...AuthorScalarSelect,
  posts: {
    take: 50,
    select: AuthorPostsSelect,
  },
} as Prisma.AuthorSelect;
