// @generated by next-prisma-flow-state-engine
// file: server/methods.ts

"use server";

import { prisma } from "../../prisma";
import type { Prisma } from "../../prisma";
import { FlowCtx, FlowPolicyError } from "../../core";
import { canTag } from "../../policies";
import { TagSelect } from "./selects";

export async function findUnique(
  args: Prisma.TagFindUniqueArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canTag("read", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.tag.findUnique({
    select: TagSelect,
    ...args,
    where: { ...args.where, ...policy.where },
  });
}

export async function findUniqueOrThrow(
  args: Prisma.TagFindUniqueOrThrowArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canTag("read", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.tag.findUniqueOrThrow({
    select: TagSelect,
    ...args,
    where: { ...args.where, ...policy.where },
  });
}

export async function findFirst(
  args?: Prisma.TagFindFirstArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canTag("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.tag.findFirst({
    select: TagSelect,
    ...args,
    where: { ...args?.where, ...policy.where },
  });
}

export async function findFirstOrThrow(
  args?: Prisma.TagFindFirstOrThrowArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canTag("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.tag.findFirstOrThrow({
    select: TagSelect,
    ...args,
    where: { ...args?.where, ...policy.where },
  });
}

export async function findMany(
  args?: Prisma.TagFindManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canTag("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.tag.findMany({
    select: TagSelect,
    ...args,
    where: { ...args?.where, ...policy.where },
  });
}

export async function create(args: Prisma.TagCreateArgs, ctx: FlowCtx = {}) {
  const policy = await canTag("create", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const result = await prisma.tag.create({
    select: TagSelect,
    ...args,
    data: { ...args.data, ...policy.data },
  });

  return result;
}

export async function createMany(
  args: Prisma.TagCreateManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canTag("create", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  // Apply policy data to each item
  const data = Array.isArray(args.data)
    ? args.data.map((item) => ({ ...item, ...policy.data }))
    : { ...args.data, ...policy.data };

  return prisma.tag.createMany({
    ...args,
    data,
  });
}

export async function update(args: Prisma.TagUpdateArgs, ctx: FlowCtx = {}) {
  const policy = await canTag("update", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const result = await prisma.tag.update({
    select: TagSelect,
    ...args,
    where: { ...args.where, ...policy.where },
    data: { ...args.data, ...policy.data },
  });

  return result;
}

export async function updateMany(
  args: Prisma.TagUpdateManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canTag("update", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.tag.updateMany({
    ...args,
    where: { ...args.where, ...policy.where },
    data: { ...args.data, ...policy.data },
  });
}

export async function upsert(args: Prisma.TagUpsertArgs, ctx: FlowCtx = {}) {
  // Check both create and update policies
  const createPolicy = await canTag("create", ctx);
  const updatePolicy = await canTag("update", ctx);

  // Need both permissions for upsert
  if (!createPolicy.ok || !updatePolicy.ok) {
    throw new FlowPolicyError("Insufficient permissions for upsert");
  }

  return prisma.tag.upsert({
    select: TagSelect,
    ...args,
    where: { ...args.where, ...updatePolicy.where },
    create: { ...args.create, ...createPolicy.data },
    update: { ...args.update, ...updatePolicy.data },
  });
}

export async function deleteOne(args: Prisma.TagDeleteArgs, ctx: FlowCtx = {}) {
  const policy = await canTag("delete", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.tag.delete({
    ...args,
    where: { ...args.where, ...policy.where },
  });
}

export async function deleteMany(
  args?: Prisma.TagDeleteManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canTag("delete", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.tag.deleteMany({
    ...args,
    where: { ...args?.where, ...policy.where },
  });
}

export async function count(args?: Prisma.TagCountArgs, ctx: FlowCtx = {}) {
  const policy = await canTag("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.tag.count({
    ...args,
    where: { ...args?.where, ...policy.where },
  });
}

export async function aggregate(
  args: Prisma.TagAggregateArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canTag("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.tag.aggregate({
    ...args,
    where: { ...args.where, ...policy.where },
  });
}

export async function groupBy<
  T extends Prisma.TagGroupByArgs,
  HasSelectOrTake extends Prisma.Or<
    Prisma.Extends<"skip", Prisma.Keys<T>>,
    Prisma.Extends<"take", Prisma.Keys<T>>
  >,
  OrderByArg extends Prisma.True extends HasSelectOrTake
    ? { orderBy: Prisma.TagGroupByArgs["orderBy"] }
    : { orderBy?: Prisma.TagGroupByArgs["orderBy"] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<
    Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
  >,
  ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<T["having"]>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [
                  Error,
                  "Field ",
                  P,
                  ` used in "having" needs to be provided in "by"`,
                ];
        }[HavingFields]
      : "take" extends Prisma.Keys<T>
        ? "orderBy" extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : "skip" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
>(
  args: Prisma.SubsetIntersection<T, Prisma.TagGroupByArgs, OrderByArg> &
    InputErrors,
  ctx: FlowCtx = {},
): Promise<
  {} extends InputErrors ? Prisma.GetTagGroupByPayload<T> : InputErrors
> {
  const policy = await canTag("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.tag.groupBy({
    ...(args as any),
    where: { ...args.where, ...policy.where },
  } as any) as any;
}
