// @generated by next-prisma-flow-state-engine
// file: server/queries.ts

"use server";

import { prisma } from "../../prisma";
import { cacheTagged, FlowCtx, FlowPolicyError } from "../../core";
import { canTag } from "../../policies";
import { TagSelect } from "./selects";
import type { Prisma } from "../../prisma";
import type { FlowTag } from "../types/schemas";

// Transform Prisma response to match FlowTag schema (null -> undefined for relations)
function transformResponse(item: any): any {
  if (!item) return item;
  const result = { ...item };
  return result;
}

function transformResponseList(items: any[]): any[] {
  return items.map(transformResponse);
}

export const getTagById = cacheTagged(async function (
  id: string,
  ctx: FlowCtx = {},
): Promise<FlowTag | null> {
  const policy = await canTag("read", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const item = (await prisma.tag.findUnique({
    where: { id: id, ...policy.where },
    select: TagSelect,
  })) as FlowTag | null;

  return transformResponse(item) as FlowTag | null;
});

export type TagListParams = {
  where?: Prisma.TagWhereInput;
  orderBy?:
    | Prisma.TagOrderByWithRelationInput
    | Prisma.TagOrderByWithRelationInput[];
  skip?: number;
  take?: number;
  cursor?: Prisma.TagWhereUniqueInput;
};

export const listTags = cacheTagged(async function (
  params: TagListParams = {},
  ctx: FlowCtx = {},
): Promise<{ items: FlowTag[]; total: number }> {
  const policy = await canTag("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const where = { ...params.where, ...policy.where };

  const [items, total] = await Promise.all([
    prisma.tag.findMany({
      where,
      orderBy: params.orderBy,
      skip: params.skip,
      take: params.take || 50,
      cursor: params.cursor,
      select: TagSelect,
    }) as Promise<FlowTag[]>,
    prisma.tag.count({ where }),
  ]);

  return { items: transformResponseList(items) as FlowTag[], total };
});

export const searchTags = cacheTagged(async function (
  query: string,
  params: Omit<TagListParams, "where"> = {},
  ctx: FlowCtx = {},
): Promise<{ items: FlowTag[]; total: number }> {
  const policy = await canTag("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const where = {
    AND: [
      policy.where,
      {
        OR: [
          { name: { contains: query, mode: "insensitive" as const } },
          { color: { contains: query, mode: "insensitive" as const } },
          { companyId: { contains: query, mode: "insensitive" as const } },
        ],
      },
    ],
  };

  const [items, total] = await Promise.all([
    prisma.tag.findMany({
      where,
      orderBy: params.orderBy,
      skip: params.skip,
      take: params.take || 50,
      cursor: params.cursor,
      select: TagSelect,
    }) as Promise<FlowTag[]>,
    prisma.tag.count({ where }),
  ]);

  return { items: transformResponseList(items) as FlowTag[], total };
});
