// @generated by next-prisma-flow-state-engine
// file: server/selects.ts

import "server-only";
import { Prisma } from "../../prisma";

// Scalar selects
export const TagScalarSelect = {
  id: true,
  name: true,
  color: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.TagSelect;
export const TagTodoScalarSelect = {
  id: true,
  title: true,
  description: true,
  status: true,
  priority: true,
  dueDate: true,
  completedAt: true,
  orderIndex: true,
  isArchived: true,
  createdAt: true,
  updatedAt: true,
  listId: true,
  userId: true,
  parentId: true,
} as Prisma.TodoSelect;
export const TagListScalarSelect = {
  id: true,
  name: true,
  description: true,
  color: true,
  icon: true,
  orderIndex: true,
  isDefault: true,
  createdAt: true,
  updatedAt: true,
  userId: true,
} as Prisma.ListSelect;
export const TagUserScalarSelect = {
  id: true,
  email: true,
  name: true,
  avatar: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.UserSelect;

// Nested relation selects
export const TagTodosListUserSelect = {
  ...TagUserScalarSelect,
  lists: false,
  todos: false,
} as Prisma.UserSelect;
export const TagTodosListSelect = {
  ...TagListScalarSelect,
  todos: false,
  user: { select: TagTodosListUserSelect },
} as Prisma.ListSelect;
export const TagTodosSubtasksListUserSelect = {
  ...TagUserScalarSelect,
  lists: false,
  todos: false,
} as Prisma.UserSelect;
export const TagTodosSubtasksListSelect = {
  ...TagListScalarSelect,
  todos: false,
  user: { select: TagTodosSubtasksListUserSelect },
} as Prisma.ListSelect;
export const TagTodosSubtasksUserListsSelect = {
  ...TagListScalarSelect,
  todos: false,
  user: false,
} as Prisma.ListSelect;
export const TagTodosSubtasksUserSelect = {
  ...TagUserScalarSelect,
  lists: {
    select: TagTodosSubtasksUserListsSelect,
    take: 50,
  },
  todos: false,
} as Prisma.UserSelect;
export const TagTodosSubtasksSelect = {
  ...TagTodoScalarSelect,
  list: { select: TagTodosSubtasksListSelect },
  tags: false,
  subtasks: false,
  parent: false,
  user: { select: TagTodosSubtasksUserSelect },
} as Prisma.TodoSelect;
export const TagTodosParentListUserSelect = {
  ...TagUserScalarSelect,
  lists: false,
  todos: false,
} as Prisma.UserSelect;
export const TagTodosParentListSelect = {
  ...TagListScalarSelect,
  todos: false,
  user: { select: TagTodosParentListUserSelect },
} as Prisma.ListSelect;
export const TagTodosParentUserListsSelect = {
  ...TagListScalarSelect,
  todos: false,
  user: false,
} as Prisma.ListSelect;
export const TagTodosParentUserSelect = {
  ...TagUserScalarSelect,
  lists: {
    select: TagTodosParentUserListsSelect,
    take: 50,
  },
  todos: false,
} as Prisma.UserSelect;
export const TagTodosParentSelect = {
  ...TagTodoScalarSelect,
  list: { select: TagTodosParentListSelect },
  tags: false,
  subtasks: false,
  parent: false,
  user: { select: TagTodosParentUserSelect },
} as Prisma.TodoSelect;
export const TagTodosUserListsSelect = {
  ...TagListScalarSelect,
  todos: false,
  user: false,
} as Prisma.ListSelect;
export const TagTodosUserSelect = {
  ...TagUserScalarSelect,
  lists: {
    select: TagTodosUserListsSelect,
    take: 50,
  },
  todos: false,
} as Prisma.UserSelect;
export const TagTodosSelect = {
  ...TagTodoScalarSelect,
  list: { select: TagTodosListSelect },
  tags: false,
  subtasks: {
    select: TagTodosSubtasksSelect,
    take: 50,
  },
  parent: { select: TagTodosParentSelect },
  user: { select: TagTodosUserSelect },
} as Prisma.TodoSelect;

// Main select
export const TagSelect = {
  ...TagScalarSelect,
  todos: {
    take: 50,
    select: TagTodosSelect,
  },
} as Prisma.TagSelect;
