// @generated by next-prisma-flow-state-engine
// file: server/methods.ts

"use server";

import { prisma } from "../../prisma";
import type { Prisma } from "../../prisma";
import { FlowCtx, FlowPolicyError } from "../../core";
import { canPost } from "../../policies";
import { PostSelect } from "./selects";
import type { FlowPost } from "../types/schemas";

export async function findUnique(
  args: Prisma.PostFindUniqueArgs,
  ctx: FlowCtx = {},
): Promise<FlowPost | null> {
  const policy = await canPost("read", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.post.findUnique({
    select: PostSelect,
    ...args,
    where: { ...args.where, ...policy.where },
  }) as Promise<FlowPost | null>;
}

export async function findUniqueOrThrow(
  args: Prisma.PostFindUniqueOrThrowArgs,
  ctx: FlowCtx = {},
): Promise<FlowPost> {
  const policy = await canPost("read", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.post.findUniqueOrThrow({
    select: PostSelect,
    ...args,
    where: { ...args.where, ...policy.where },
  }) as Promise<FlowPost>;
}

export async function findFirst(
  args?: Prisma.PostFindFirstArgs,
  ctx: FlowCtx = {},
): Promise<FlowPost | null> {
  const policy = await canPost("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.post.findFirst({
    select: PostSelect,
    ...args,
    where: { ...args?.where, ...policy.where },
  }) as Promise<FlowPost | null>;
}

export async function findFirstOrThrow(
  args?: Prisma.PostFindFirstOrThrowArgs,
  ctx: FlowCtx = {},
): Promise<FlowPost> {
  const policy = await canPost("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.post.findFirstOrThrow({
    select: PostSelect,
    ...args,
    where: { ...args?.where, ...policy.where },
  }) as Promise<FlowPost>;
}

export async function findMany(
  args?: Prisma.PostFindManyArgs,
  ctx: FlowCtx = {},
): Promise<FlowPost[]> {
  const policy = await canPost("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.post.findMany({
    select: PostSelect,
    ...args,
    where: { ...args?.where, ...policy.where },
  }) as Promise<FlowPost[]>;
}

export async function create(
  args: Prisma.PostCreateArgs,
  ctx: FlowCtx = {},
): Promise<FlowPost> {
  const policy = await canPost("create", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const result = (await prisma.post.create({
    select: PostSelect,
    ...args,
    data: { ...args.data, ...policy.data },
  })) as FlowPost;

  return result;
}

export async function createMany(
  args: Prisma.PostCreateManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canPost("create", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  // Apply policy data to each item
  const data = Array.isArray(args.data)
    ? args.data.map((item) => ({ ...item, ...policy.data }))
    : { ...args.data, ...policy.data };

  return prisma.post.createMany({
    ...args,
    data,
  });
}

export async function update(
  args: Prisma.PostUpdateArgs,
  ctx: FlowCtx = {},
): Promise<FlowPost> {
  const policy = await canPost("update", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const result = (await prisma.post.update({
    select: PostSelect,
    ...args,
    where: { ...args.where, ...policy.where },
    data: { ...args.data, ...policy.data },
  })) as FlowPost;

  return result;
}

export async function updateMany(
  args: Prisma.PostUpdateManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canPost("update", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.post.updateMany({
    ...args,
    where: { ...args.where, ...policy.where },
    data: { ...args.data, ...policy.data },
  });
}

export async function upsert(
  args: Prisma.PostUpsertArgs,
  ctx: FlowCtx = {},
): Promise<FlowPost> {
  // Check both create and update policies
  const createPolicy = await canPost("create", ctx);
  const updatePolicy = await canPost("update", ctx);

  // Need both permissions for upsert
  if (!createPolicy.ok || !updatePolicy.ok) {
    throw new FlowPolicyError("Insufficient permissions for upsert");
  }

  return prisma.post.upsert({
    select: PostSelect,
    ...args,
    where: { ...args.where, ...updatePolicy.where },
    create: { ...args.create, ...createPolicy.data },
    update: { ...args.update, ...updatePolicy.data },
  }) as Promise<FlowPost>;
}

export async function deleteOne(
  args: Prisma.PostDeleteArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canPost("delete", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.post.delete({
    ...args,
    where: { ...args.where, ...policy.where },
  });
}

export async function deleteMany(
  args?: Prisma.PostDeleteManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canPost("delete", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.post.deleteMany({
    ...args,
    where: { ...args?.where, ...policy.where },
  });
}

export async function count(args?: Prisma.PostCountArgs, ctx: FlowCtx = {}) {
  const policy = await canPost("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.post.count({
    ...args,
    where: { ...args?.where, ...policy.where },
  });
}

export async function aggregate(
  args: Prisma.PostAggregateArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canPost("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.post.aggregate({
    ...args,
    where: { ...args.where, ...policy.where },
  });
}

export async function groupBy<
  T extends Prisma.PostGroupByArgs,
  HasSelectOrTake extends Prisma.Or<
    Prisma.Extends<"skip", Prisma.Keys<T>>,
    Prisma.Extends<"take", Prisma.Keys<T>>
  >,
  OrderByArg extends Prisma.True extends HasSelectOrTake
    ? { orderBy: Prisma.PostGroupByArgs["orderBy"] }
    : { orderBy?: Prisma.PostGroupByArgs["orderBy"] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<
    Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
  >,
  ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<T["having"]>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [
                  Error,
                  "Field ",
                  P,
                  ` used in "having" needs to be provided in "by"`,
                ];
        }[HavingFields]
      : "take" extends Prisma.Keys<T>
        ? "orderBy" extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : "skip" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
>(
  args: Prisma.SubsetIntersection<T, Prisma.PostGroupByArgs, OrderByArg> &
    InputErrors,
  ctx: FlowCtx = {},
): Promise<
  {} extends InputErrors ? Prisma.GetPostGroupByPayload<T> : InputErrors
> {
  const policy = await canPost("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.post.groupBy({
    ...(args as any),
    where: { ...args.where, ...policy.where },
  } as any) as any;
}
