// @generated by next-prisma-flow-state-engine
// file: server/selects.ts

import "server-only";
import { Prisma } from "../../prisma";

// Scalar selects
export const PostScalarSelect = {
  id: true,
  title: true,
  slug: true,
  excerpt: true,
  content: true,
  published: true,
  publishedAt: true,
  createdAt: true,
  updatedAt: true,
  authorId: true,
} as Prisma.PostSelect;
export const PostAuthorScalarSelect = {
  id: true,
  email: true,
  name: true,
  bio: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.AuthorSelect;
export const PostTagScalarSelect = {
  id: true,
  name: true,
  slug: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.TagSelect;

// Nested relation selects
export const PostAuthorSelect = {
  ...PostAuthorScalarSelect,
  posts: false,
} as Prisma.AuthorSelect;
export const PostTagsSelect = {
  ...PostTagScalarSelect,
  posts: false,
} as Prisma.TagSelect;

// Main select
export const PostSelect = {
  ...PostScalarSelect,
  author: {
    select: PostAuthorSelect,
  },
  tags: {
    take: 50,
    select: PostTagsSelect,
  },
} as Prisma.PostSelect;
