// @generated by next-prisma-flow-state-engine
// file: client/hooks.ts

"use client";

import {
  useQuery,
  useMutation,
  useQueryClient,
  UseQueryOptions,
  UseMutationOptions,
} from "@tanstack/react-query";
import { useState, useCallback } from "react";
import { keys } from "../../core/keys";
import { useFlowCtx } from "../../core/provider";
import type { TodoListParams } from "../server/queries";
import type {
  FlowTodo,
  FlowTodoCreate,
  FlowTodoUpdate,
} from "../types/schemas";

export function useTodo(
  id: string,
  options?: Omit<UseQueryOptions<FlowTodo | null>, "queryKey" | "queryFn">,
) {
  const ctx = useFlowCtx();

  return useQuery({
    queryKey: keys.m("Todo").byId(String(id)),
    queryFn: async () => {
      const { getTodoById } = await import("../server/queries");
      return getTodoById(id, ctx);
    },
    ...options,
  });
}

export function useTodoList(
  params?: TodoListParams,
  options?: Omit<
    UseQueryOptions<{ items: FlowTodo[]; total: number }>,
    "queryKey" | "queryFn"
  >,
) {
  const ctx = useFlowCtx();
  const [localParams, setLocalParams] = useState(params || {});

  const query = useQuery({
    queryKey: keys.m("Todo").list(localParams),
    queryFn: async () => {
      const { listTodos } = await import("../server/queries");
      return listTodos(localParams, ctx);
    },
    ...options,
  });

  return {
    ...query,
    params: localParams,
    setParams: setLocalParams,
    nextPage: useCallback(() => {
      if (query.data && localParams.take) {
        const skip = (localParams.skip || 0) + localParams.take;
        if (skip < query.data.total) {
          setLocalParams((prev) => ({ ...prev, skip }));
        }
      }
    }, [query.data, localParams]),
    previousPage: useCallback(() => {
      if (localParams.skip && localParams.take) {
        const skip = Math.max(0, localParams.skip - localParams.take);
        setLocalParams((prev) => ({ ...prev, skip }));
      }
    }, [localParams]),
  };
}

export function useCreateTodo(
  options?: UseMutationOptions<FlowTodo, Error, FlowTodoCreate>,
) {
  const ctx = useFlowCtx();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: FlowTodoCreate) => {
      const { createTodo } = await import("../server/actions");
      return createTodo(data, ctx);
    },
    onSuccess: (data, variables, context) => {
      queryClient.invalidateQueries({ queryKey: [keys.m("Todo").tag()] });
      options?.onSuccess?.(data, variables, context);
    },
    ...options,
  });
}

export function useUpdateTodo(
  id: string,
  options?: UseMutationOptions<FlowTodo, Error, FlowTodoUpdate>,
) {
  const ctx = useFlowCtx();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: FlowTodoUpdate) => {
      const { updateTodo } = await import("../server/actions");
      return updateTodo(id, data, ctx);
    },
    onMutate: async (newData) => {
      // Optimistic update
      await queryClient.cancelQueries({
        queryKey: keys.m("Todo").byId(String(id)),
      });
      const previousData = queryClient.getQueryData(
        keys.m("Todo").byId(String(id)),
      );

      queryClient.setQueryData(keys.m("Todo").byId(String(id)), (old: any) =>
        old ? { ...old, ...newData } : old,
      );

      return { previousData };
    },
    onError: (err, newData, context: any) => {
      // Revert optimistic update on error
      if (context?.previousData) {
        queryClient.setQueryData(
          keys.m("Todo").byId(String(id)),
          context.previousData,
        );
      }
      options?.onError?.(err, newData, context);
    },
    onSettled: () => {
      queryClient.invalidateQueries({
        queryKey: keys.m("Todo").byId(String(id)),
      });
      queryClient.invalidateQueries({ queryKey: [keys.m("Todo").tag()] });
    },
    ...options,
  });
}

export function useDeleteTodo(
  options?: UseMutationOptions<void, Error, string>,
) {
  const ctx = useFlowCtx();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { deleteTodo } = await import("../server/actions");
      return deleteTodo(id, ctx);
    },
    onSuccess: (data, id, context) => {
      queryClient.invalidateQueries({
        queryKey: keys.m("Todo").byId(String(id)),
      });
      queryClient.invalidateQueries({ queryKey: [keys.m("Todo").tag()] });
      options?.onSuccess?.(data, id, context);
    },
    ...options,
  });
}

export function useTodoMutation(options?: {
  mode: "create" | "update";
  id?: string;
  onSuccess?: (data: FlowTodo) => void;
  onError?: (error: Error) => void;
}) {
  const { mode = "create", id, onSuccess, onError } = options || {};

  const createMutation = useCreateTodo({
    onSuccess,
    onError,
  });

  const updateMutation = useUpdateTodo(id!, {
    onSuccess,
    onError,
  });

  if (mode === "update" && id) {
    return updateMutation;
  }

  return createMutation as typeof createMutation;
}
