// @generated by next-prisma-flow-state-engine
// file: server/selects.ts

import "server-only";
import { Prisma } from "../../prisma";

// Scalar selects
export const TodoListTemplateScalarSelect = {
  id: true,
  name: true,
} as Prisma.TodoListTemplateSelect;

// Main select
export const TodoListTemplateSelect = {
  ...TodoListTemplateScalarSelect,
} as Prisma.TodoListTemplateSelect;
