// @generated by next-prisma-flow-state-engine
// file: core/provider.tsx

"use client";
import { createContext, useContext } from "react";
import type { FlowCtx } from "./ctx";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const Ctx = createContext<FlowCtx | null>(null);
let qc: QueryClient | null = null;

export function FlowProvider({
  ctx,
  children,
}: {
  ctx: FlowCtx;
  children: any;
}) {
  if (!qc) qc = new QueryClient();
  return (
    <Ctx.Provider value={ctx}>
      <QueryClientProvider client={qc}>{children}</QueryClientProvider>
    </Ctx.Provider>
  );
}
export function useFlowCtx() {
  const c = useContext(Ctx);
  if (!c) throw new Error("FlowProvider missing");
  return c;
}
