// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-08-01T17:20:41.600Z

import {
	PostCreateManyInputSchema,
	PostFindFirstArgsSchema,
	PostFindManyArgsSchema,
	PostUncheckedCreateInputSchema,
	PostUncheckedUpdateInputSchema,
	PostWhereInputSchema,
	PostWhereUniqueInputSchema,
} from "../zod";

export const schemas = {
	whereUnique: PostWhereUniqueInputSchema,
	where: PostWhereInputSchema,
	createInput: PostUncheckedCreateInputSchema,
	createManyInput: PostCreateManyInputSchema,
	updateInput: PostUncheckedUpdateInputSchema,
	findFirstArgs: PostFindFirstArgsSchema,
	findManyArgs: PostFindManyArgsSchema,
};
