// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-11T12:47:11.421Z

import {
	PostCreateInputSchema,
	PostCreateManyInputSchema,
	PostFindFirstArgsSchema,
	PostFindManyArgsSchema,
	PostUpdateInputSchema,
	PostWhereInputSchema,
	PostWhereUniqueInputSchema,
} from "../zod";

export const schemas = {
	whereUnique: PostWhereUniqueInputSchema,
	where: PostWhereInputSchema,
	createInput: PostCreateInputSchema,
	createManyInput: PostCreateManyInputSchema,
	updateInput: PostUpdateInputSchema,
	findFirstArgs: PostFindFirstArgsSchema,
	findManyArgs: PostFindManyArgsSchema,
};
