// @generated by next-prisma-flow-state-engine
// file: server/queries.ts

"use server";

import { prisma } from "../../prisma";
import { cacheTagged, FlowCtx, FlowPolicyError } from "../../core";
import { canPost } from "../../policies";
import { PostSelect } from "./selects";
import type { Prisma } from "../../prisma";

// Transform Prisma response to match FlowPost schema (null -> undefined for relations)
function transformResponse(item: any): any {
  if (!item) return item;
  const result = { ...item };
  return result;
}

function transformResponseList(items: any[]): any[] {
  return items.map(transformResponse);
}

export const getPostById = cacheTagged(async function (
  id: string,
  ctx: FlowCtx = {},
) {
  const policy = await canPost("read", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const item = await prisma.post.findUnique({
    where: { id: id, ...policy.where },
    select: PostSelect,
  });

  return transformResponse(item);
});

export type PostListParams = {
  where?: Prisma.PostWhereInput;
  orderBy?:
    | Prisma.PostOrderByWithRelationInput
    | Prisma.PostOrderByWithRelationInput[];
  skip?: number;
  take?: number;
  cursor?: Prisma.PostWhereUniqueInput;
};

export const listPosts = cacheTagged(async function (
  params: PostListParams = {},
  ctx: FlowCtx = {},
) {
  const policy = await canPost("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const where = { ...params.where, ...policy.where };

  const [items, total] = await Promise.all([
    prisma.post.findMany({
      where,
      orderBy: params.orderBy,
      skip: params.skip,
      take: params.take || 50,
      cursor: params.cursor,
      select: PostSelect,
    }),
    prisma.post.count({ where }),
  ]);

  return { items: transformResponseList(items), total };
});

export const searchPosts = cacheTagged(async function (
  query: string,
  params: Omit<PostListParams, "where"> = {},
  ctx: FlowCtx = {},
) {
  const policy = await canPost("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const where = {
    AND: [
      policy.where,
      {
        OR: [
          { title: { contains: query, mode: "insensitive" as const } },
          { content: { contains: query, mode: "insensitive" as const } },
          { authorId: { contains: query, mode: "insensitive" as const } },
        ],
      },
    ],
  };

  const [items, total] = await Promise.all([
    prisma.post.findMany({
      where,
      orderBy: params.orderBy,
      skip: params.skip,
      take: params.take || 50,
      cursor: params.cursor,
      select: PostSelect,
    }),
    prisma.post.count({ where }),
  ]);

  return { items: transformResponseList(items), total };
});
