// @generated by next-prisma-flow-state-engine
// file: server/selects.ts

import "server-only";
import { Prisma } from "../../prisma";

// Scalar selects
export const PostScalarSelect = {
  id: true,
  title: true,
  content: true,
  authorId: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.PostSelect;
export const PostUserScalarSelect = {
  id: true,
  email: true,
  name: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.UserSelect;
export const PostCommentScalarSelect = {
  id: true,
  content: true,
  postId: true,
  authorId: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.CommentSelect;

// Nested relation selects
export const PostAuthorCommentsSelect = {
  ...PostCommentScalarSelect,
  author: false,
  post: false,
} as Prisma.CommentSelect;
export const PostAuthorSelect = {
  ...PostUserScalarSelect,
  posts: false,
  comments: {
    select: PostAuthorCommentsSelect,
    take: 50,
  },
} as Prisma.UserSelect;
export const PostCommentsAuthorSelect = {
  ...PostUserScalarSelect,
  posts: false,
  comments: false,
} as Prisma.UserSelect;
export const PostCommentsSelect = {
  ...PostCommentScalarSelect,
  author: { select: PostCommentsAuthorSelect },
  post: false,
} as Prisma.CommentSelect;

// Main select
export const PostSelect = {
  ...PostScalarSelect,
  author: {
    select: PostAuthorSelect,
  },
  comments: {
    take: 50,
    select: PostCommentsSelect,
  },
} as Prisma.PostSelect;
