// @generated by next-prisma-flow-state-engine
// file: client/forms.ts

"use client";

import { useCallback, useEffect, useState, useRef } from "react";
import {
  useForm,
  type UseFormReturn,
  type UseFormProps,
  type Path,
  type PathValue,
  type FieldErrors,
} from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { AuthorCreateSchema, AuthorUpdateSchema } from "../types/schemas";
import type {
  FlowAuthor,
  FlowAuthorCreate,
  FlowAuthorUpdate,
} from "../types/schemas";
import { useAuthor, useCreateAuthor, useUpdateAuthor } from "./hooks";
import {
  useAuthorFormAutosave,
  useAuthorFormFieldTracking,
  useAuthorFormHistory,
} from "./composables";

export type AuthorFieldState = {
  isDirty: boolean;
  isTouched: boolean;
  error?: any;
  current: any;
  original?: any;
  hasChanged?: boolean;
};

export type AuthorDirtyField = {
  field: string;
  original?: any;
  current: any;
};

export type AuthorAutosaveConfig = {
  enabled: boolean;
  debounceMs?: number;
  fields?: string[];
  onFieldSave?: (field: string, value: any) => void;
  onFieldError?: (field: string, error: Error) => void;
};

export type AuthorFormFeatures = {
  autosave?: AuthorAutosaveConfig | boolean;
  tracking?: boolean;
  history?:
    | {
        enabled: boolean;
        maxHistorySize?: number;
      }
    | boolean;
};

// Create form options
export type AuthorCreateFormOptions = {
  defaultValues?: Partial<FlowAuthorCreate>;
  onSuccess?: (data: FlowAuthor) => void;
  onError?: (error: Error) => void;
  formOptions?: Omit<
    UseFormProps<FlowAuthorCreate>,
    "resolver" | "defaultValues"
  >;
  features?: AuthorFormFeatures;
};

export type AuthorUpdateFormOptions = {
  defaultValues?: Partial<FlowAuthorUpdate>;
  onSuccess?: (data: FlowAuthor) => void;
  onError?: (error: Error) => void;
  formOptions?: Omit<
    UseFormProps<FlowAuthorUpdate>,
    "resolver" | "defaultValues"
  >;
  features?: AuthorFormFeatures;
};

function extractScalarFields(data: any): any {
  const result: any = {};
  Object.keys(data).forEach((key) => {
    const value = data[key];
    if (
      value === null ||
      (typeof value !== "object" && !Array.isArray(value))
    ) {
      result[key] = value;
    }
  });
  return result;
}

export function useCreateAuthorForm(options?: AuthorCreateFormOptions) {
  const { defaultValues, onSuccess, onError, formOptions, features } =
    options || {};

  const form = useForm<FlowAuthorCreate>({
    ...formOptions,
    resolver: zodResolver(AuthorCreateSchema),
    defaultValues: defaultValues as FlowAuthorCreate,
  });

  const mutation = useCreateAuthor({
    onSuccess: (data) => {
      form.reset();
      onSuccess?.(data);
    },
    onError,
  });

  // Field operations
  const getFieldState = useCallback(
    (name: Path<FlowAuthorCreate>): AuthorFieldState => {
      const fieldState = form.getFieldState(name);
      return {
        isDirty: fieldState.isDirty,
        isTouched: fieldState.isTouched,
        error: fieldState.error,
        current: form.getValues(name),
        original: (form.formState.defaultValues as any)?.[name],
      };
    },
    [form],
  );

  const resetField = useCallback(
    (name: Path<FlowAuthorCreate>) => {
      form.resetField(name);
    },
    [form],
  );

  const setFieldValue = useCallback(
    <T extends Path<FlowAuthorCreate>>(
      name: T,
      value: PathValue<FlowAuthorCreate, T>,
      options?: {
        shouldValidate?: boolean;
        shouldDirty?: boolean;
        shouldTouch?: boolean;
      },
    ) => {
      form.setValue(name, value, options);
    },
    [form],
  );

  const validateField = useCallback(
    (name: Path<FlowAuthorCreate>) => {
      return form.trigger(name);
    },
    [form],
  );

  const clearFieldError = useCallback(
    (name: Path<FlowAuthorCreate>) => {
      form.clearErrors(name);
    },
    [form],
  );

  const batchUpdate = useCallback(
    (updates: Partial<FlowAuthorCreate>) => {
      Object.entries(updates).forEach(([key, value]) => {
        form.setValue(key as Path<FlowAuthorCreate>, value as any);
      });
    },
    [form],
  );

  const getDirtyFields = useCallback((): AuthorDirtyField[] => {
    const dirtyFields: AuthorDirtyField[] = [];
    Object.keys(form.formState.dirtyFields).forEach((key) => {
      if ((form.formState.dirtyFields as any)[key]) {
        dirtyFields.push({
          field: key,
          original: (form.formState.defaultValues as any)?.[key],
          current: form.getValues(key as Path<FlowAuthorCreate>),
        });
      }
    });
    return dirtyFields;
  }, [form]);

  // Submit handler
  const submit = useCallback(
    (data: FlowAuthorCreate) => {
      console.log("[AuthorCreateForm] Submitting:", data);
      return mutation.mutate(data);
    },
    [mutation],
  );

  const onInvalid = useCallback((errors: any) => {
    console.error("[AuthorCreateForm] Validation failed:", errors);
  }, []);

  // Always call composables (no conditional hooks)
  const autosaveConfig =
    typeof features?.autosave === "object"
      ? features.autosave
      : { enabled: !!features?.autosave };
  const autosave = useAuthorFormAutosave(form, mutation, autosaveConfig);

  const tracking = useAuthorFormFieldTracking(form);

  const historyConfig =
    typeof features?.history === "object"
      ? features.history
      : { enabled: !!features?.history };
  const history = useAuthorFormHistory(form, historyConfig);

  return {
    form,
    mutation,
    submit: form.handleSubmit(submit, onInvalid),
    isSubmitting: mutation.isPending,
    error: mutation.error,
    isSuccess: mutation.isSuccess,
    reset: () => form.reset(),
    // Field operations
    getFieldState,
    resetField,
    setFieldValue,
    validateField,
    clearFieldError,
    batchUpdate,
    getDirtyFields,
    // Include features if enabled
    ...(autosaveConfig.enabled ? { autosave } : {}),
    ...(features?.tracking ? { tracking } : {}),
    ...(historyConfig.enabled ? { history } : {}),
  };
}

export function useUpdateAuthorForm(
  id: string,
  options?: AuthorUpdateFormOptions,
) {
  const { defaultValues, onSuccess, onError, formOptions, features } =
    options || {};

  const originalRef = useRef<FlowAuthor>();

  // Fetch existing data
  const { data: existingData } = useAuthor(id);

  // Initialize form
  const form = useForm<FlowAuthorUpdate>({
    ...formOptions,
    resolver: zodResolver(AuthorUpdateSchema),
    defaultValues: defaultValues as FlowAuthorUpdate,
  });

  // Track autosave ref to use in useEffect
  const autosaveRef = useRef<ReturnType<typeof useAuthorFormAutosave>>();

  // Update form when existing data loads
  useEffect(() => {
    if (existingData) {
      originalRef.current = existingData;
      const scalarData = extractScalarFields(existingData);
      console.log("[AuthorUpdateForm] Loading data:", scalarData);

      // Pause autosave during form reset to prevent loops
      if (autosaveRef.current?.pauseAutosave) {
        autosaveRef.current.pauseAutosave(() => {
          form.reset(scalarData as FlowAuthorUpdate, {
            keepDirtyValues: true,
            keepErrors: true,
          });
        });
      } else {
        form.reset(scalarData as FlowAuthorUpdate, {
          keepDirtyValues: true,
          keepErrors: true,
        });
      }
    }
  }, [existingData, form]);

  // Update mutation
  const mutation = useUpdateAuthor(id, {
    onSuccess,
    onError,
  });

  // Field operations with original comparison
  const getFieldState = useCallback(
    (name: Path<FlowAuthorUpdate>): AuthorFieldState => {
      const fieldState = form.getFieldState(name);
      const currentValue = form.getValues(name);
      const originalValue = originalRef.current?.[name as keyof FlowAuthor];
      return {
        isDirty: fieldState.isDirty,
        isTouched: fieldState.isTouched,
        error: fieldState.error,
        current: currentValue,
        original: originalValue,
        hasChanged: currentValue !== originalValue,
      };
    },
    [form],
  );

  const resetField = useCallback(
    (name: Path<FlowAuthorUpdate>) => {
      const originalValue = originalRef.current?.[name as keyof FlowAuthor];
      form.setValue(name, originalValue as any);
      form.clearErrors(name);
    },
    [form],
  );

  const setFieldValue = useCallback(
    <T extends Path<FlowAuthorUpdate>>(
      name: T,
      value: PathValue<FlowAuthorUpdate, T>,
      options?: {
        shouldValidate?: boolean;
        shouldDirty?: boolean;
        shouldTouch?: boolean;
      },
    ) => {
      form.setValue(name, value, options);
    },
    [form],
  );

  const validateField = useCallback(
    (name: Path<FlowAuthorUpdate>) => {
      return form.trigger(name);
    },
    [form],
  );

  const clearFieldError = useCallback(
    (name: Path<FlowAuthorUpdate>) => {
      form.clearErrors(name);
    },
    [form],
  );

  const batchUpdate = useCallback(
    (updates: Partial<FlowAuthorUpdate>) => {
      Object.entries(updates).forEach(([key, value]) => {
        form.setValue(key as Path<FlowAuthorUpdate>, value as any);
      });
    },
    [form],
  );

  const getDirtyFields = useCallback((): AuthorDirtyField[] => {
    const dirtyFields: AuthorDirtyField[] = [];
    Object.keys(form.formState.dirtyFields).forEach((key) => {
      if ((form.formState.dirtyFields as any)[key]) {
        dirtyFields.push({
          field: key,
          original: originalRef.current?.[key as keyof FlowAuthor],
          current: form.getValues(key as Path<FlowAuthorUpdate>),
        });
      }
    });
    return dirtyFields;
  }, [form]);

  // Submit handler
  const submit = useCallback(
    (data: FlowAuthorUpdate) => {
      console.log("[AuthorUpdateForm] Submitting:", data);
      return mutation.mutate(data);
    },
    [mutation],
  );

  const onInvalid = useCallback((errors: any) => {
    console.error("[AuthorUpdateForm] Validation failed:", errors);
  }, []);

  // Always call composables (no conditional hooks)
  const autosaveConfig =
    typeof features?.autosave === "object"
      ? features.autosave
      : { enabled: !!features?.autosave };
  const autosave = useAuthorFormAutosave(form, mutation, autosaveConfig);

  // Store autosave ref for use in useEffect
  useEffect(() => {
    autosaveRef.current = autosave;
  }, [autosave]);

  const tracking = useAuthorFormFieldTracking(form, originalRef.current);

  const historyConfig =
    typeof features?.history === "object"
      ? features.history
      : { enabled: !!features?.history };
  const history = useAuthorFormHistory(form, historyConfig);

  return {
    form,
    mutation,
    original: originalRef.current,
    submit: form.handleSubmit(submit, onInvalid),
    isSubmitting: mutation.isPending,
    error: mutation.error,
    isSuccess: mutation.isSuccess,
    reset: () => form.reset(extractScalarFields(originalRef.current || {})),
    // Field operations
    getFieldState,
    resetField,
    setFieldValue,
    validateField,
    clearFieldError,
    batchUpdate,
    getDirtyFields,
    // Include features if enabled
    ...(autosaveConfig.enabled ? { autosave } : {}),
    ...(features?.tracking ? { tracking } : {}),
    ...(historyConfig.enabled ? { history } : {}),
  };
}

export type AuthorCreateFormProps = {
  form: UseFormReturn<FlowAuthorCreate>;
  onSubmit: () => void;
  isSubmitting: boolean;
  error?: Error | null;
};

export type AuthorUpdateFormProps = {
  form: UseFormReturn<FlowAuthorUpdate>;
  onSubmit: () => void;
  isSubmitting: boolean;
  error?: Error | null;
  original?: FlowAuthor;
};
