// @generated by next-prisma-flow-state-engine
// file: client/field.tsx

"use client";

import {} from "react";
import { type Path } from "react-hook-form";
import {
  FlowField,
  type FlowFieldProps,
  FlowFieldTransforms,
} from "../../core/field-wrapper";
import { useFlowFormContext } from "../../core/form-provider";
import type { FlowTagCreate, FlowTagUpdate } from "../types/schemas";

/**
 * Valid field names for Tag forms
 */
export type TagFieldName = Path<FlowTagCreate> | Path<FlowTagUpdate>;

/**
 * Props for TagFormField component
 */
export interface TagFormFieldProps extends Omit<FlowFieldProps, "name"> {
  /**
   * The field name - type-safe with autocomplete
   */
  name: TagFieldName;
}

/**
 * Type-safe form field for Tag
 * Works seamlessly with shadcn/ui form components
 *
 * @example
 * ```tsx
 * <TagFormField
 *   name="title"
 *   render={({ field }) => (
 *     <FormItem>
 *       <FormLabel>Title</FormLabel>
 *       <FormControl>
 *         <Input {...field} />
 *       </FormControl>
 *       <FormDescription>
 *         Enter a descriptive title
 *       </FormDescription>
 *       <FormMessage />
 *     </FormItem>
 *   )}
 * />
 * ```
 */
export function TagFormField({ name, ...props }: TagFormFieldProps) {
  return <FlowField name={name as any} {...props} />;
}

/**
 * Common field transforms for Tag
 *
 * @example
 * ```tsx
 * <TagFormField
 *   name="price"
 *   transform={TagFieldTransforms.number}
 *   render={({ field }) => <Input type="number" {...field} />}
 * />
 * ```
 */
export const TagFieldTransforms = {
  /**
   * Transform for date fields
   */
  date: FlowFieldTransforms.dateToISO,

  /**
   * Trim whitespace from text fields
   */
  text: FlowFieldTransforms.trim,
};

/**
 * Hook to get field value and setter
 *
 * @example
 * ```tsx
 * function MyComponent() {
 *   const [title, setTitle] = useTagFieldValue("title");
 *   return <input value={title} onChange={e => setTitle(e.target.value)} />;
 * }
 * ```
 */
export function useTagFieldValue(name: TagFieldName) {
  const { form } = useFlowFormContext();
  const value = form.watch(name as any);
  const setValue = (newValue: any) => {
    form.setValue(name as any, newValue, {
      shouldValidate: true,
      shouldDirty: true,
      shouldTouch: true,
    });
  };
  return [value, setValue] as const;
}

/**
 * Hook to get field state
 *
 * @example
 * ```tsx
 * function MyField() {
 *   const fieldState = useTagFieldState("title");
 *   return (
 *     <div>
 *       {fieldState.isDirty && <span>Modified</span>}
 *       {fieldState.error && <span>{fieldState.error.message}</span>}
 *     </div>
 *   );
 * }
 * ```
 */
export function useTagFieldState(name: TagFieldName) {
  const { form } = useFlowFormContext();
  return form.getFieldState(name as any);
}

/**
 * Hook to get field error
 *
 * @example
 * ```tsx
 * function MyField() {
 *   const error = useTagFieldError("email");
 *   if (error) {
 *     return <span className="text-red-500">{error.message}</span>;
 *   }
 *   return null;
 * }
 * ```
 */
export function useTagFieldError(name: TagFieldName) {
  const { form } = useFlowFormContext();
  const fieldState = form.getFieldState(name as any);
  return fieldState.error;
}
