// @generated by next-prisma-flow-state-engine
// file: server/queries.ts

"use server";

import { prisma } from "../../prisma";
import { cacheTagged, FlowCtx, FlowPolicyError } from "../../core";
import { canCompany } from "../../policies";
import { CompanySelect } from "./selects";
import type { Prisma } from "../../prisma";
import type { FlowCompany } from "../types/schemas";

// Transform Prisma response to match FlowCompany schema (null -> undefined for relations)
function transformResponse(item: any): any {
  if (!item) return item;
  const result = { ...item };
  return result;
}

function transformResponseList(items: any[]): any[] {
  return items.map(transformResponse);
}

export const getCompanyById = cacheTagged(async function (
  id: string,
  ctx: FlowCtx = {},
): Promise<FlowCompany | null> {
  const policy = await canCompany("read", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const item = (await prisma.company.findUnique({
    where: { id: id, ...policy.where },
    select: CompanySelect,
  })) as FlowCompany | null;

  return transformResponse(item) as FlowCompany | null;
});

export type CompanyListParams = {
  where?: Prisma.CompanyWhereInput;
  orderBy?:
    | Prisma.CompanyOrderByWithRelationInput
    | Prisma.CompanyOrderByWithRelationInput[];
  skip?: number;
  take?: number;
  cursor?: Prisma.CompanyWhereUniqueInput;
};

export const listCompanys = cacheTagged(async function (
  params: CompanyListParams = {},
  ctx: FlowCtx = {},
): Promise<{ items: FlowCompany[]; total: number }> {
  const policy = await canCompany("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const where = { ...params.where, ...policy.where };

  const [items, total] = await Promise.all([
    prisma.company.findMany({
      where,
      orderBy: params.orderBy,
      skip: params.skip,
      take: params.take || 50,
      cursor: params.cursor,
      select: CompanySelect,
    }) as Promise<FlowCompany[]>,
    prisma.company.count({ where }),
  ]);

  return { items: transformResponseList(items) as FlowCompany[], total };
});

export const searchCompanys = cacheTagged(async function (
  query: string,
  params: Omit<CompanyListParams, "where"> = {},
  ctx: FlowCtx = {},
): Promise<{ items: FlowCompany[]; total: number }> {
  const policy = await canCompany("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const where = {
    AND: [
      policy.where,
      {
        OR: [
          { name: { contains: query, mode: "insensitive" as const } },
          { slug: { contains: query, mode: "insensitive" as const } },
          { logo: { contains: query, mode: "insensitive" as const } },
          { plan: { contains: query, mode: "insensitive" as const } },
        ],
      },
    ],
  };

  const [items, total] = await Promise.all([
    prisma.company.findMany({
      where,
      orderBy: params.orderBy,
      skip: params.skip,
      take: params.take || 50,
      cursor: params.cursor,
      select: CompanySelect,
    }) as Promise<FlowCompany[]>,
    prisma.company.count({ where }),
  ]);

  return { items: transformResponseList(items) as FlowCompany[], total };
});
