// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-09T17:45:48.136Z

import {
	CommentCreateInputSchema,
	CommentCreateManyInputSchema,
	CommentFindFirstArgsSchema,
	CommentFindManyArgsSchema,
	CommentUpdateInputSchema,
	CommentWhereInputSchema,
	CommentWhereUniqueInputSchema,
} from "../zod";

export const schemas = {
	whereUnique: CommentWhereUniqueInputSchema,
	where: CommentWhereInputSchema,
	createInput: CommentCreateInputSchema,
	createManyInput: CommentCreateManyInputSchema,
	updateInput: CommentUpdateInputSchema,
	findFirstArgs: CommentFindFirstArgsSchema,
	findManyArgs: CommentFindManyArgsSchema,
	// Adding create and update for form factory compatibility
	create: CommentCreateInputSchema,
	update: CommentUpdateInputSchema,
};
