// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-11T12:47:11.422Z

import {
	CommentCreateInputSchema,
	CommentCreateManyInputSchema,
	CommentFindFirstArgsSchema,
	CommentFindManyArgsSchema,
	CommentUpdateInputSchema,
	CommentWhereInputSchema,
	CommentWhereUniqueInputSchema,
} from "../zod";

export const schemas = {
	whereUnique: CommentWhereUniqueInputSchema,
	where: CommentWhereInputSchema,
	createInput: CommentCreateInputSchema,
	createManyInput: CommentCreateManyInputSchema,
	updateInput: CommentUpdateInputSchema,
	findFirstArgs: CommentFindFirstArgsSchema,
	findManyArgs: CommentFindManyArgsSchema,
};
