// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-09T17:45:48.136Z

import type { Prisma } from "../prisma";

export type CreateInput = Prisma.CommentCreateInput;
export type CreateManyInput = Prisma.CommentCreateManyInput;
export type UpdateInput = Prisma.CommentUpdateInput;
export type UpdateManyInput = Prisma.CommentUncheckedUpdateManyInput;
export type WhereInput = Prisma.CommentWhereInput;
export type WhereUniqueInput = Prisma.CommentWhereUniqueInput;
export type OrderByInput = Prisma.CommentOrderByWithRelationInput;
export type SelectInput = Prisma.CommentSelect;
export type IncludeInput = Prisma.CommentInclude;

export type ModelType = Prisma.CommentGetPayload<{
	select: {
		id: true;
		content: true;
		createdAt: true;
		updatedAt: true;
	};
}>;

export type Options = {
	orderBy?: OrderByInput;
};

export type CreateManyOptions = {
	include?: IncludeInput;
	select?: SelectInput;
};

export interface Relationships extends Record<string, { where: any; many: boolean }> {
	post: { where: Prisma.PostWhereUniqueInput; many: false };
}
