// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-16T09:35:00.636Z

import { prisma } from "../prisma";
import type { SelectInput } from "./types";

export const model = "category" as const;
export const modelPrismaClient = prisma[model];
export const select: SelectInput = {
	id: true,
	name: true,
	color: true,
	createdAt: true,
};
