// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-11T12:47:11.419Z

import { useAtomValue, useSetAtom } from "jotai";
import { entityAtomFamily, errorAtom, pendingPatchesAtom } from "./atoms";
import {
	countAtom,
	countByFieldAtomFamily,
	entityBusyFamily,
	entityLoadableFamily,
	hasAnyAtom,
	listByFieldAtomFamily,
	listLoadable,
	loadingAtom,
	pagedAtom,
	searchAtom,
	selectedAtom,
	selectedIdAtom,
} from "./derived";

import { makeRelationHelpers } from "../shared/hooks/relation-helper";
import { makeUseFormHook } from "../shared/hooks/use-form-factory";
import { useAutoload } from "../shared/hooks/useAutoload";
import { createAtom, deleteAtom, loadEntityAtom, loadsListAtom, updateAtom, upsertAtom } from "./fx";
import { schemas } from "./schemas";
import type { CreateInput, ModelType, Relationships, UpdateInput } from "./types";

/**
 * Hook for managing the complete categories collection with comprehensive state management.
 *
 * Provides access to the full categories list along with loading states, error handling,
 * and all necessary CRUD operations. This hook manages the global state for categories
 * and automatically handles loading indicators and error states.
 *
 * @param {Object} opts - Configuration options
 * @param {boolean} [opts.autoLoad=true] - Whether to automatically load data when component mounts
 *
 * @returns {Object} Complete categories management interface
 * @returns {Array} data - Array of categories (empty array when loading or on error)
 * @returns {number} count - Total number of categories available
 * @returns {boolean} hasAny - Quick check if any categories exist
 * @returns {boolean} loading - True when fetching data or performing operations
 * @returns {Error|null} error - Last error that occurred, null if no errors
 * @returns {Function} createCategory - Creates a new category
 * @returns {Function} updateCategory - Updates an existing category
 * @returns {Function} upsertCategory - Upserts a category
 * @returns {Function} deleteCategory - Deletes a category by ID
 * @returns {Function} fetchAll - Refreshes the entire categories list
 *
 * @example
 * ```tsx
 * function CategoriesList() {
 *   const { data, loading, error, createCategory, updateCategory, deleteCategory } = useCategories();
 *
 *   if (loading) return <div>Loading categories...</div>;
 *   if (error) return <div>Error: {error.message}</div>;
 *
 *   return (
 *     <div>
 *       {data.map(category => (
 *         <CategoryItem key={category.id} category={category} onUpdate={updateCategory} onDelete={deleteCategory} />
 *       ))}
 *     </div>
 *   );
 * }
 * ```
 */
export function useCategories(opts: { autoLoad?: boolean } = { autoLoad: true }) {
	const loadable = useAtomValue(listLoadable);
	const busy = useAtomValue(loadingAtom);
	const count = useAtomValue(countAtom);
	const hasAny = useAtomValue(hasAnyAtom);
	const lastError = useAtomValue(errorAtom);

	const createCategory = useSetAtom(createAtom);
	const updateCategory = useSetAtom(updateAtom);
	const deleteCategory = useSetAtom(deleteAtom);
	const upsertCategory = useSetAtom(upsertAtom);
	const fetchAll = useSetAtom(loadsListAtom);
	const fetchById = useSetAtom(loadEntityAtom);

	useAutoload(
		() => opts.autoLoad !== false && !busy && !hasAny,
		() => fetchAll({}, {}),
	);

	return {
		/* data */
		data: loadable.state === "hasData" ? loadable.data : [],
		count,
		hasAny,

		/* meta */
		loading: busy || loadable.state === "loading",
		error: loadable.state === "hasError" ? loadable.error : lastError,

		/* actions */
		createCategory,
		updateCategory,
		deleteCategory,
		upsertCategory,
		fetchAll,
		fetchById,
	};
}

/**
 * Hook for managing a specific category by ID with optimistic updates and error handling.
 *
 * Provides granular control over individual categories, including fetching, updating, and deleting.
 * The hook automatically manages loading states and errors specific to this category instance.
 * Actions are pre-bound with the category ID for convenience.
 *
 * @param {string} id - The unique identifier of the category to manage
 * @param {Object} opts - Configuration options
 * @param {boolean} [opts.autoLoad=true] - Whether to automatically load data when component mounts
 *
 * @returns {Object} Single category management interface
 * @returns {Object|null} data - The category data object, null if not found or loading
 * @returns {boolean} loading - True when fetching or performing operations on this category
 * @returns {Error|null} error - Last error related to operations on this category
 * @returns {Function} updateCategory - Updates this specific category with provided data
 * @returns {Function} deleteCategory - Deletes this specific category
 * @returns {Function} fetch - Fetches/refreshes this specific category from the server
 * @returns {Object} relations - relationship helpers
 *
 * @example
 * ```tsx
 * function CategoryDetail({ categoryId }: { categoryId: string }) {
 *   const { data, loading, error, updateCategory, deleteCategory } = useCategory(categoryId);
 *
 *   if (loading) return <div>Loading category...</div>;
 *   if (error) return <div>Error loading category: {error.message}</div>;
 *   if (!data) return <div>Category not found</div>;
 *
 *   const handleSave = (formData) => {
 *     updateCategory(formData); // ID is automatically included
 *   };
 *
 *   return (
 *     <div>
 *       <h1>{data.title}</h1>
 *       <p>{data.content}</p>
 *       <button onClick={() => deleteCategory()}>Delete</button>
 *     </div>
 *   );
 * }
 * ```
 */
export function useCategory(id: string, opts: { autoLoad?: boolean } = { autoLoad: true }) {
	const category = useAtomValue(entityAtomFamily(id));
	const loadable = useAtomValue(entityLoadableFamily(id));
	const busyItem = useAtomValue(entityBusyFamily(id));
	const lastError = useAtomValue(errorAtom);
	const pendingPatches = useAtomValue(pendingPatchesAtom);

	const updateCategory = useSetAtom(updateAtom);
	const deleteCategory = useSetAtom(deleteAtom);
	const fetch = useSetAtom(loadEntityAtom);

	const relations = makeRelationHelpers<Relationships>(id, updateCategory);

	useAutoload(
		() => opts.autoLoad !== false && !busyItem && !category && !pendingPatches[id],
		() => fetch({ id }),
	);

	return {
		/* data */
		data: category,

		/* meta */
		loading: busyItem || loadable.state === "loading",
		error: lastError,

		/* actions */
		updateCategory: (data: UpdateInput) => updateCategory({ id, data }),
		deleteCategory: () => deleteCategory(id),
		fetch: () => fetch({ id }),

		/* relations */
		relations,
	};
}

export const useCategoryForm = makeUseFormHook<ModelType, CreateInput, UpdateInput>({
	create: schemas.createInput,
	update: schemas.updateInput,
});

export const useSelectedId = () => useAtomValue(selectedIdAtom);
export const useSelected = () => useAtomValue(selectedAtom);
export const useSetSelectedId = () => useSetAtom(selectedIdAtom);

export function useListByFieldValue<K extends keyof ModelType>(field: K, value: ModelType[K]) {
	const fam = listByFieldAtomFamily(field);
	return useAtomValue(fam(value));
}

export function usePagedList(page: number, pageSize = 10) {
	return useAtomValue(pagedAtom({ page, pageSize }));
}

export function useSearch(query: string) {
	return useAtomValue(searchAtom(query));
}

export function useCountByFieldValue<K extends keyof ModelType>(field: K, value: ModelType[K]) {
	const fam = countByFieldAtomFamily(field);
	return useAtomValue(fam(value));
}
