// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-09T17:45:48.134Z

import {
	CategoryCreateInputSchema,
	CategoryCreateManyInputSchema,
	CategoryFindFirstArgsSchema,
	CategoryFindManyArgsSchema,
	CategoryUpdateInputSchema,
	CategoryWhereInputSchema,
	CategoryWhereUniqueInputSchema,
} from "../zod";

export const schemas = {
	whereUnique: CategoryWhereUniqueInputSchema,
	where: CategoryWhereInputSchema,
	createInput: CategoryCreateInputSchema,
	createManyInput: CategoryCreateManyInputSchema,
	updateInput: CategoryUpdateInputSchema,
	findFirstArgs: CategoryFindFirstArgsSchema,
	findManyArgs: CategoryFindManyArgsSchema,
	// Adding create and update for form factory compatibility
	create: CategoryCreateInputSchema,
	update: CategoryUpdateInputSchema,
};
