// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-13T11:36:20.957Z

import {
	CategoryCreateManyInputSchema,
	CategoryFindFirstArgsSchema,
	CategoryFindManyArgsSchema,
	CategoryUncheckedCreateInputSchema,
	CategoryUncheckedUpdateInputSchema,
	CategoryWhereInputSchema,
	CategoryWhereUniqueInputSchema,
} from "../zod";

export const schemas = {
	whereUnique: CategoryWhereUniqueInputSchema,
	where: CategoryWhereInputSchema,
	createInput: CategoryUncheckedCreateInputSchema,
	createManyInput: CategoryCreateManyInputSchema,
	updateInput: CategoryUncheckedUpdateInputSchema,
	findFirstArgs: CategoryFindFirstArgsSchema,
	findManyArgs: CategoryFindManyArgsSchema,
};
