// @generated by next-prisma-flow-state-engine
// file: core/ctx.ts

export type FlowCtx = {
  userId?: string | null;
  tenantId?: string | null; // value that should match the DB's tenantId column on your models
  role?: string | null;
  roles?: string[] | null; // For multi-role support
};
export type CtxProvider = () => Promise<FlowCtx> | FlowCtx;
