// @generated by next-prisma-flow-state-engine
// file: server/selects.ts

import "server-only";
import { Prisma } from "../../prisma";

// Scalar selects
export const TagScalarSelect = {
  id: true,
  name: true,
  slug: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.TagSelect;
export const TagPostScalarSelect = {
  id: true,
  title: true,
  slug: true,
  excerpt: true,
  content: true,
  published: true,
  publishedAt: true,
  createdAt: true,
  updatedAt: true,
  authorId: true,
} as Prisma.PostSelect;
export const TagAuthorScalarSelect = {
  id: true,
  email: true,
  name: true,
  bio: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.AuthorSelect;

// Nested relation selects
export const TagPostsAuthorSelect = {
  ...TagAuthorScalarSelect,
  posts: false,
} as Prisma.AuthorSelect;
export const TagPostsSelect = {
  ...TagPostScalarSelect,
  author: { select: TagPostsAuthorSelect },
  tags: false,
} as Prisma.PostSelect;

// Main select
export const TagSelect = {
  ...TagScalarSelect,
  posts: {
    take: 50,
    select: TagPostsSelect,
  },
} as Prisma.TagSelect;
