// @generated by next-prisma-flow-state-engine
// file: index.ts

// Tree-shakeable named exports
export * as TagServer from "./server";
export * as TagClient from "./client";
export * as TagTypes from "./types";

// Direct exports for common usage
export {
  // Hooks
  useTag,
  useTagList,
  useCreateTag,
  useUpdateTag,
  useDeleteTag,
  useTagMutation,
} from "./client/hooks";

export {
  // Forms
  useTagForm,
  useTagQuickForm,
  type TagFormOptions,
  type TagFormProps,
} from "./client/forms";

export {
  // Schemas
  TagCreateSchema,
  TagUpdateSchema,
  TagFilterSchema,
  type FlowTag,
  type FlowTagCreate,
  type FlowTagUpdate,
  type FlowTagFilter,
} from "./types/schemas";

export {
  // Types
  type TagWithRelations,
  type TagListItem,
  type TagPage,
  type TagCursor,
} from "./types/types";

// Server-only exports (for server components/actions)
export type { TagListParams } from "./server/queries";
