// @generated by next-prisma-flow-state-engine
// file: server/methods.ts

"use server";

import { prisma } from "../../prisma";
import type { Prisma } from "../../prisma";
import { FlowCtx, FlowPolicyError, deepMergePrismaData } from "../../core";
import { canList } from "../../policies";
import { ListSelect } from "./selects";
import type { FlowList } from "../types/schemas";

export async function findUnique(
  args: Prisma.ListFindUniqueArgs,
  ctx: FlowCtx = {},
): Promise<FlowList | null> {
  const policy = await canList("read", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.list.findUnique({
    select: ListSelect,
    ...args,
    where: { ...args.where, ...policy.where },
  }) as Promise<FlowList | null>;
}

export async function findUniqueOrThrow(
  args: Prisma.ListFindUniqueOrThrowArgs,
  ctx: FlowCtx = {},
): Promise<FlowList> {
  const policy = await canList("read", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.list.findUniqueOrThrow({
    select: ListSelect,
    ...args,
    where: { ...args.where, ...policy.where },
  }) as Promise<FlowList>;
}

export async function findFirst(
  args?: Prisma.ListFindFirstArgs,
  ctx: FlowCtx = {},
): Promise<FlowList | null> {
  const policy = await canList("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.list.findFirst({
    select: ListSelect,
    ...args,
    where: { ...args?.where, ...policy.where },
  }) as Promise<FlowList | null>;
}

export async function findFirstOrThrow(
  args?: Prisma.ListFindFirstOrThrowArgs,
  ctx: FlowCtx = {},
): Promise<FlowList> {
  const policy = await canList("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.list.findFirstOrThrow({
    select: ListSelect,
    ...args,
    where: { ...args?.where, ...policy.where },
  }) as Promise<FlowList>;
}

export async function findMany(
  args?: Prisma.ListFindManyArgs,
  ctx: FlowCtx = {},
): Promise<FlowList[]> {
  const policy = await canList("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.list.findMany({
    select: ListSelect,
    ...args,
    where: { ...args?.where, ...policy.where },
  }) as Promise<FlowList[]>;
}

export async function create(
  args: Prisma.ListCreateArgs,
  ctx: FlowCtx = {},
): Promise<FlowList> {
  const policy = await canList("create", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const result = (await prisma.list.create({
    select: ListSelect,
    ...args,
    data: deepMergePrismaData(args.data, policy.data || {}, "List"),
  })) as FlowList;

  return result;
}

export async function createMany(
  args: Prisma.ListCreateManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canList("create", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  // Apply policy data to each item using deep merge
  const data = Array.isArray(args.data)
    ? args.data.map((item) =>
        deepMergePrismaData(item, policy.data || {}, "List"),
      )
    : deepMergePrismaData(args.data, policy.data || {});

  return prisma.list.createMany({
    ...args,
    data,
  });
}

export async function update(
  args: Prisma.ListUpdateArgs,
  ctx: FlowCtx = {},
): Promise<FlowList> {
  const policy = await canList("update", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const result = (await prisma.list.update({
    select: ListSelect,
    ...args,
    where: { ...args.where, ...policy.where },
    data: deepMergePrismaData(args.data, policy.data || {}, "List"),
  })) as FlowList;

  return result;
}

export async function updateMany(
  args: Prisma.ListUpdateManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canList("update", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.list.updateMany({
    ...args,
    where: { ...args.where, ...policy.where },
    data: deepMergePrismaData(args.data, policy.data || {}, "List"),
  });
}

export async function upsert(
  args: Prisma.ListUpsertArgs,
  ctx: FlowCtx = {},
): Promise<FlowList> {
  // Check both create and update policies
  const createPolicy = await canList("create", ctx);
  const updatePolicy = await canList("update", ctx);

  // Need both permissions for upsert
  if (!createPolicy.ok || !updatePolicy.ok) {
    throw new FlowPolicyError("Insufficient permissions for upsert");
  }

  return prisma.list.upsert({
    select: ListSelect,
    ...args,
    where: { ...args.where, ...updatePolicy.where },
    create: deepMergePrismaData(args.create, createPolicy.data || {}, "List"),
    update: deepMergePrismaData(args.update, updatePolicy.data || {}, "List"),
  }) as Promise<FlowList>;
}

export async function deleteOne(
  args: Prisma.ListDeleteArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canList("delete", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.list.delete({
    ...args,
    where: { ...args.where, ...policy.where },
  });
}

export async function deleteMany(
  args?: Prisma.ListDeleteManyArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canList("delete", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.list.deleteMany({
    ...args,
    where: { ...args?.where, ...policy.where },
  });
}

export async function count(args?: Prisma.ListCountArgs, ctx: FlowCtx = {}) {
  const policy = await canList("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.list.count({
    ...args,
    where: { ...args?.where, ...policy.where },
  });
}

export async function aggregate(
  args: Prisma.ListAggregateArgs,
  ctx: FlowCtx = {},
) {
  const policy = await canList("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.list.aggregate({
    ...args,
    where: { ...args.where, ...policy.where },
  });
}

export async function groupBy<
  T extends Prisma.ListGroupByArgs,
  HasSelectOrTake extends Prisma.Or<
    Prisma.Extends<"skip", Prisma.Keys<T>>,
    Prisma.Extends<"take", Prisma.Keys<T>>
  >,
  OrderByArg extends Prisma.True extends HasSelectOrTake
    ? { orderBy: Prisma.ListGroupByArgs["orderBy"] }
    : { orderBy?: Prisma.ListGroupByArgs["orderBy"] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<
    Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
  >,
  ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<T["having"]>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [
                  Error,
                  "Field ",
                  P,
                  ` used in "having" needs to be provided in "by"`,
                ];
        }[HavingFields]
      : "take" extends Prisma.Keys<T>
        ? "orderBy" extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : "skip" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
>(
  args: Prisma.SubsetIntersection<T, Prisma.ListGroupByArgs, OrderByArg> &
    InputErrors,
  ctx: FlowCtx = {},
): Promise<
  {} extends InputErrors ? Prisma.GetListGroupByPayload<T> : InputErrors
> {
  const policy = await canList("list", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  return prisma.list.groupBy({
    ...(args as any),
    where: { ...args.where, ...policy.where },
  } as any) as any;
}
