// @generated by next-prisma-flow-state-engine
// file: server/selects.ts

import "server-only";
import { Prisma } from "../../prisma";

// Scalar selects
export const ListScalarSelect = {
  id: true,
  name: true,
  description: true,
  color: true,
  icon: true,
  orderIndex: true,
  isDefault: true,
  createdAt: true,
  updatedAt: true,
  userId: true,
} as Prisma.ListSelect;
export const ListTodoScalarSelect = {
  id: true,
  title: true,
  description: true,
  status: true,
  priority: true,
  dueDate: true,
  completedAt: true,
  orderIndex: true,
  isArchived: true,
  createdAt: true,
  updatedAt: true,
  listId: true,
  userId: true,
  parentId: true,
} as Prisma.TodoSelect;
export const ListTagScalarSelect = {
  id: true,
  name: true,
  color: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.TagSelect;
export const ListUserScalarSelect = {
  id: true,
  email: true,
  name: true,
  avatar: true,
  createdAt: true,
  updatedAt: true,
} as Prisma.UserSelect;

// Nested relation selects
export const ListTodosTagsSelect = {
  ...ListTagScalarSelect,
  todos: false,
} as Prisma.TagSelect;
export const ListTodosSubtasksTagsSelect = {
  ...ListTagScalarSelect,
  todos: false,
} as Prisma.TagSelect;
export const ListTodosSubtasksUserSelect = {
  ...ListUserScalarSelect,
  lists: false,
  todos: false,
} as Prisma.UserSelect;
export const ListTodosSubtasksSelect = {
  ...ListTodoScalarSelect,
  list: false,
  tags: {
    select: ListTodosSubtasksTagsSelect,
    take: 50,
  },
  subtasks: false,
  parent: false,
  user: { select: ListTodosSubtasksUserSelect },
} as Prisma.TodoSelect;
export const ListTodosParentTagsSelect = {
  ...ListTagScalarSelect,
  todos: false,
} as Prisma.TagSelect;
export const ListTodosParentUserSelect = {
  ...ListUserScalarSelect,
  lists: false,
  todos: false,
} as Prisma.UserSelect;
export const ListTodosParentSelect = {
  ...ListTodoScalarSelect,
  list: false,
  tags: {
    select: ListTodosParentTagsSelect,
    take: 50,
  },
  subtasks: false,
  parent: false,
  user: { select: ListTodosParentUserSelect },
} as Prisma.TodoSelect;
export const ListTodosUserSelect = {
  ...ListUserScalarSelect,
  lists: false,
  todos: false,
} as Prisma.UserSelect;
export const ListTodosSelect = {
  ...ListTodoScalarSelect,
  list: false,
  tags: {
    select: ListTodosTagsSelect,
    take: 50,
  },
  subtasks: {
    select: ListTodosSubtasksSelect,
    take: 50,
  },
  parent: { select: ListTodosParentSelect },
  user: { select: ListTodosUserSelect },
} as Prisma.TodoSelect;
export const ListUserTodosTagsSelect = {
  ...ListTagScalarSelect,
  todos: false,
} as Prisma.TagSelect;
export const ListUserTodosSubtasksTagsSelect = {
  ...ListTagScalarSelect,
  todos: false,
} as Prisma.TagSelect;
export const ListUserTodosSubtasksSelect = {
  ...ListTodoScalarSelect,
  list: false,
  tags: {
    select: ListUserTodosSubtasksTagsSelect,
    take: 50,
  },
  subtasks: false,
  parent: false,
  user: false,
} as Prisma.TodoSelect;
export const ListUserTodosParentTagsSelect = {
  ...ListTagScalarSelect,
  todos: false,
} as Prisma.TagSelect;
export const ListUserTodosParentSelect = {
  ...ListTodoScalarSelect,
  list: false,
  tags: {
    select: ListUserTodosParentTagsSelect,
    take: 50,
  },
  subtasks: false,
  parent: false,
  user: false,
} as Prisma.TodoSelect;
export const ListUserTodosSelect = {
  ...ListTodoScalarSelect,
  list: false,
  tags: {
    select: ListUserTodosTagsSelect,
    take: 50,
  },
  subtasks: {
    select: ListUserTodosSubtasksSelect,
    take: 50,
  },
  parent: { select: ListUserTodosParentSelect },
  user: false,
} as Prisma.TodoSelect;
export const ListUserSelect = {
  ...ListUserScalarSelect,
  lists: false,
  todos: {
    select: ListUserTodosSelect,
    take: 50,
  },
} as Prisma.UserSelect;

// Main select
export const ListSelect = {
  ...ListScalarSelect,
  todos: {
    take: 50,
    select: ListTodosSelect,
  },
  user: {
    select: ListUserSelect,
  },
} as Prisma.ListSelect;
