// @generated by next-prisma-flow-state-engine
// file: client/forms.ts

"use client";

import { useCallback, useEffect, useState, useRef } from "react";
import {
  useForm,
  type UseFormReturn,
  type UseFormProps,
  type Path,
  type PathValue,
  type FieldErrors,
} from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { CompanyCreateSchema, CompanyUpdateSchema } from "../types/schemas";
import type {
  FlowCompany,
  FlowCompanyCreate,
  FlowCompanyUpdate,
} from "../types/schemas";
import { useCompany, useCreateCompany, useUpdateCompany } from "./hooks";
import {
  useCompanyFormAutosave,
  useCompanyFormFieldTracking,
  useCompanyFormHistory,
} from "./composables";

export type CompanyFieldState = {
  isDirty: boolean;
  isTouched: boolean;
  error?: any;
  current: any;
  original?: any;
  hasChanged?: boolean;
};

export type CompanyDirtyField = {
  field: string;
  original?: any;
  current: any;
};

export type CompanyAutosaveConfig = {
  enabled: boolean;
  debounceMs?: number;
  fields?: string[];
  onFieldSave?: (field: string, value: any) => void;
  onFieldError?: (field: string, error: Error) => void;
};

export type CompanyFormFeatures = {
  autosave?: CompanyAutosaveConfig | boolean;
  tracking?: boolean;
  history?:
    | {
        enabled: boolean;
        maxHistorySize?: number;
      }
    | boolean;
};

// Create form options
export type CompanyCreateFormOptions = {
  defaultValues?: Partial<FlowCompanyCreate>;
  onSuccess?: (data: FlowCompany) => void;
  onError?: (error: Error) => void;
  formOptions?: Omit<
    UseFormProps<FlowCompanyCreate>,
    "resolver" | "defaultValues"
  >;
  features?: CompanyFormFeatures;
};

export type CompanyUpdateFormOptions = {
  defaultValues?: Partial<FlowCompanyUpdate>;
  onSuccess?: (data: FlowCompany) => void;
  onError?: (error: Error) => void;
  formOptions?: Omit<
    UseFormProps<FlowCompanyUpdate>,
    "resolver" | "defaultValues"
  >;
  features?: CompanyFormFeatures;
};

function extractScalarFields(data: any): any {
  const result: any = {};
  Object.keys(data).forEach((key) => {
    const value = data[key];
    if (
      value === null ||
      (typeof value !== "object" && !Array.isArray(value))
    ) {
      result[key] = value;
    }
  });
  return result;
}

export function useCreateCompanyForm(options?: CompanyCreateFormOptions) {
  const { defaultValues, onSuccess, onError, formOptions, features } =
    options || {};

  const form = useForm<FlowCompanyCreate>({
    ...formOptions,
    resolver: zodResolver(CompanyCreateSchema),
    defaultValues: defaultValues as FlowCompanyCreate,
  });

  const mutation = useCreateCompany({
    onSuccess: (data) => {
      form.reset();
      onSuccess?.(data);
    },
    onError,
  });

  // Field operations
  const getFieldState = useCallback(
    (name: Path<FlowCompanyCreate>): CompanyFieldState => {
      const fieldState = form.getFieldState(name);
      return {
        isDirty: fieldState.isDirty,
        isTouched: fieldState.isTouched,
        error: fieldState.error,
        current: form.getValues(name),
        original: (form.formState.defaultValues as any)?.[name],
      };
    },
    [form],
  );

  const resetField = useCallback(
    (name: Path<FlowCompanyCreate>) => {
      form.resetField(name);
    },
    [form],
  );

  const setFieldValue = useCallback(
    <T extends Path<FlowCompanyCreate>>(
      name: T,
      value: PathValue<FlowCompanyCreate, T>,
      options?: {
        shouldValidate?: boolean;
        shouldDirty?: boolean;
        shouldTouch?: boolean;
      },
    ) => {
      form.setValue(name, value, options);
    },
    [form],
  );

  const validateField = useCallback(
    (name: Path<FlowCompanyCreate>) => {
      return form.trigger(name);
    },
    [form],
  );

  const clearFieldError = useCallback(
    (name: Path<FlowCompanyCreate>) => {
      form.clearErrors(name);
    },
    [form],
  );

  const batchUpdate = useCallback(
    (updates: Partial<FlowCompanyCreate>) => {
      Object.entries(updates).forEach(([key, value]) => {
        form.setValue(key as Path<FlowCompanyCreate>, value as any);
      });
    },
    [form],
  );

  const getDirtyFields = useCallback((): CompanyDirtyField[] => {
    const dirtyFields: CompanyDirtyField[] = [];
    Object.keys(form.formState.dirtyFields).forEach((key) => {
      if ((form.formState.dirtyFields as any)[key]) {
        dirtyFields.push({
          field: key,
          original: (form.formState.defaultValues as any)?.[key],
          current: form.getValues(key as Path<FlowCompanyCreate>),
        });
      }
    });
    return dirtyFields;
  }, [form]);

  // Submit handler
  const submit = useCallback(
    (data: FlowCompanyCreate) => {
      console.log("[CompanyCreateForm] Submitting:", data);
      return mutation.mutate(data);
    },
    [mutation],
  );

  const onInvalid = useCallback((errors: any) => {
    console.error("[CompanyCreateForm] Validation failed:", errors);
  }, []);

  // Always call composables (no conditional hooks)
  const autosaveConfig =
    typeof features?.autosave === "object"
      ? features.autosave
      : { enabled: !!features?.autosave };
  const autosave = useCompanyFormAutosave(form, mutation, autosaveConfig);

  const tracking = useCompanyFormFieldTracking(form);

  const historyConfig =
    typeof features?.history === "object"
      ? features.history
      : { enabled: !!features?.history };
  const history = useCompanyFormHistory(form, historyConfig);

  return {
    form,
    mutation,
    submit: form.handleSubmit(submit, onInvalid),
    isSubmitting: mutation.isPending,
    error: mutation.error,
    isSuccess: mutation.isSuccess,
    reset: () => form.reset(),
    // Field operations
    getFieldState,
    resetField,
    setFieldValue,
    validateField,
    clearFieldError,
    batchUpdate,
    getDirtyFields,
    // Include features if enabled
    ...(autosaveConfig.enabled ? { autosave } : {}),
    ...(features?.tracking ? { tracking } : {}),
    ...(historyConfig.enabled ? { history } : {}),
  };
}

export function useUpdateCompanyForm(
  id: string,
  options?: CompanyUpdateFormOptions,
) {
  const { defaultValues, onSuccess, onError, formOptions, features } =
    options || {};

  const originalRef = useRef<FlowCompany>();

  // Fetch existing data
  const { data: existingData } = useCompany(id);

  // Initialize form
  const form = useForm<FlowCompanyUpdate>({
    ...formOptions,
    resolver: zodResolver(CompanyUpdateSchema),
    defaultValues: defaultValues as FlowCompanyUpdate,
  });

  // Track autosave ref to use in useEffect
  const autosaveRef = useRef<ReturnType<typeof useCompanyFormAutosave>>();

  // Update form when existing data loads
  useEffect(() => {
    if (existingData) {
      originalRef.current = existingData;
      const scalarData = extractScalarFields(existingData);
      console.log("[CompanyUpdateForm] Loading data:", scalarData);

      // Pause autosave during form reset to prevent loops
      if (autosaveRef.current?.pauseAutosave) {
        autosaveRef.current.pauseAutosave(() => {
          form.reset(scalarData as FlowCompanyUpdate, {
            keepDirtyValues: true,
            keepErrors: true,
          });
        });
      } else {
        form.reset(scalarData as FlowCompanyUpdate, {
          keepDirtyValues: true,
          keepErrors: true,
        });
      }
    }
  }, [existingData, form]);

  // Update mutation
  const mutation = useUpdateCompany(id, {
    onSuccess,
    onError,
  });

  // Field operations with original comparison
  const getFieldState = useCallback(
    (name: Path<FlowCompanyUpdate>): CompanyFieldState => {
      const fieldState = form.getFieldState(name);
      const currentValue = form.getValues(name);
      const originalValue = originalRef.current?.[name as keyof FlowCompany];
      return {
        isDirty: fieldState.isDirty,
        isTouched: fieldState.isTouched,
        error: fieldState.error,
        current: currentValue,
        original: originalValue,
        hasChanged: currentValue !== originalValue,
      };
    },
    [form],
  );

  const resetField = useCallback(
    (name: Path<FlowCompanyUpdate>) => {
      const originalValue = originalRef.current?.[name as keyof FlowCompany];
      form.setValue(name, originalValue as any);
      form.clearErrors(name);
    },
    [form],
  );

  const setFieldValue = useCallback(
    <T extends Path<FlowCompanyUpdate>>(
      name: T,
      value: PathValue<FlowCompanyUpdate, T>,
      options?: {
        shouldValidate?: boolean;
        shouldDirty?: boolean;
        shouldTouch?: boolean;
      },
    ) => {
      form.setValue(name, value, options);
    },
    [form],
  );

  const validateField = useCallback(
    (name: Path<FlowCompanyUpdate>) => {
      return form.trigger(name);
    },
    [form],
  );

  const clearFieldError = useCallback(
    (name: Path<FlowCompanyUpdate>) => {
      form.clearErrors(name);
    },
    [form],
  );

  const batchUpdate = useCallback(
    (updates: Partial<FlowCompanyUpdate>) => {
      Object.entries(updates).forEach(([key, value]) => {
        form.setValue(key as Path<FlowCompanyUpdate>, value as any);
      });
    },
    [form],
  );

  const getDirtyFields = useCallback((): CompanyDirtyField[] => {
    const dirtyFields: CompanyDirtyField[] = [];
    Object.keys(form.formState.dirtyFields).forEach((key) => {
      if ((form.formState.dirtyFields as any)[key]) {
        dirtyFields.push({
          field: key,
          original: originalRef.current?.[key as keyof FlowCompany],
          current: form.getValues(key as Path<FlowCompanyUpdate>),
        });
      }
    });
    return dirtyFields;
  }, [form]);

  // Submit handler
  const submit = useCallback(
    (data: FlowCompanyUpdate) => {
      console.log("[CompanyUpdateForm] Submitting:", data);
      return mutation.mutate(data);
    },
    [mutation],
  );

  const onInvalid = useCallback((errors: any) => {
    console.error("[CompanyUpdateForm] Validation failed:", errors);
  }, []);

  // Always call composables (no conditional hooks)
  const autosaveConfig =
    typeof features?.autosave === "object"
      ? features.autosave
      : { enabled: !!features?.autosave };
  const autosave = useCompanyFormAutosave(form, mutation, autosaveConfig);

  // Store autosave ref for use in useEffect
  useEffect(() => {
    autosaveRef.current = autosave;
  }, [autosave]);

  const tracking = useCompanyFormFieldTracking(form, originalRef.current);

  const historyConfig =
    typeof features?.history === "object"
      ? features.history
      : { enabled: !!features?.history };
  const history = useCompanyFormHistory(form, historyConfig);

  return {
    form,
    mutation,
    original: originalRef.current,
    submit: form.handleSubmit(submit, onInvalid),
    isSubmitting: mutation.isPending,
    error: mutation.error,
    isSuccess: mutation.isSuccess,
    reset: () => form.reset(extractScalarFields(originalRef.current || {})),
    // Field operations
    getFieldState,
    resetField,
    setFieldValue,
    validateField,
    clearFieldError,
    batchUpdate,
    getDirtyFields,
    // Include features if enabled
    ...(autosaveConfig.enabled ? { autosave } : {}),
    ...(features?.tracking ? { tracking } : {}),
    ...(historyConfig.enabled ? { history } : {}),
  };
}

export type CompanyCreateFormProps = {
  form: UseFormReturn<FlowCompanyCreate>;
  onSubmit: () => void;
  isSubmitting: boolean;
  error?: Error | null;
};

export type CompanyUpdateFormProps = {
  form: UseFormReturn<FlowCompanyUpdate>;
  onSubmit: () => void;
  isSubmitting: boolean;
  error?: Error | null;
  original?: FlowCompany;
};
