// @generated by next-prisma-flow-state-engine
// file: client/hooks.ts

"use client";

import {
  useQuery,
  useMutation,
  useQueryClient,
  UseQueryOptions,
  UseMutationOptions,
} from "@tanstack/react-query";
import { useState, useCallback } from "react";
import { keys } from "../../core/keys";
import { useFlowCtx } from "../../core/provider";
import type { CompanyListParams } from "../server/queries";
import type {
  FlowCompany,
  FlowCompanyCreate,
  FlowCompanyUpdate,
} from "../types/schemas";

export function useCompany(
  id: string,
  options?: Omit<UseQueryOptions<FlowCompany | null>, "queryKey" | "queryFn">,
) {
  const ctx = useFlowCtx();

  return useQuery({
    queryKey: keys.m("Company").byId(String(id)),
    queryFn: async () => {
      const { getCompanyById } = await import("../server/queries");
      return getCompanyById(id, ctx);
    },
    ...options,
  });
}

export function useCompanyList(
  params?: CompanyListParams,
  options?: Omit<
    UseQueryOptions<{ items: FlowCompany[]; total: number }>,
    "queryKey" | "queryFn"
  >,
) {
  const ctx = useFlowCtx();
  const [localParams, setLocalParams] = useState(params || {});

  const query = useQuery({
    queryKey: keys.m("Company").list(localParams),
    queryFn: async () => {
      const { listCompanys } = await import("../server/queries");
      return listCompanys(localParams, ctx);
    },
    ...options,
  });

  return {
    ...query,
    params: localParams,
    setParams: setLocalParams,
    nextPage: useCallback(() => {
      if (query.data && localParams.take) {
        const skip = (localParams.skip || 0) + localParams.take;
        if (skip < query.data.total) {
          setLocalParams((prev) => ({ ...prev, skip }));
        }
      }
    }, [query.data, localParams]),
    previousPage: useCallback(() => {
      if (localParams.skip && localParams.take) {
        const skip = Math.max(0, localParams.skip - localParams.take);
        setLocalParams((prev) => ({ ...prev, skip }));
      }
    }, [localParams]),
  };
}

export function useCreateCompany(
  options?: UseMutationOptions<FlowCompany, Error, FlowCompanyCreate>,
) {
  const ctx = useFlowCtx();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: FlowCompanyCreate) => {
      const { createCompany } = await import("../server/actions");
      return createCompany(data, ctx);
    },
    onSuccess: (data, variables, context) => {
      queryClient.invalidateQueries({ queryKey: [keys.m("Company").tag()] });
      options?.onSuccess?.(data, variables, context);
    },
    ...options,
  });
}

export function useUpdateCompany(
  id: string,
  options?: UseMutationOptions<FlowCompany, Error, FlowCompanyUpdate>,
) {
  const ctx = useFlowCtx();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: FlowCompanyUpdate) => {
      const { updateCompany } = await import("../server/actions");
      return updateCompany(id, data, ctx);
    },
    onMutate: async (newData) => {
      // Optimistic update
      await queryClient.cancelQueries({
        queryKey: keys.m("Company").byId(String(id)),
      });
      const previousData = queryClient.getQueryData(
        keys.m("Company").byId(String(id)),
      );

      queryClient.setQueryData(
        keys.m("Company").byId(String(id)),
        (old: any) => (old ? { ...old, ...newData } : old),
      );

      return { previousData };
    },
    onError: (err, newData, context: any) => {
      // Revert optimistic update on error
      if (context?.previousData) {
        queryClient.setQueryData(
          keys.m("Company").byId(String(id)),
          context.previousData,
        );
      }
      options?.onError?.(err, newData, context);
    },
    onSettled: () => {
      queryClient.invalidateQueries({
        queryKey: keys.m("Company").byId(String(id)),
      });
      queryClient.invalidateQueries({ queryKey: [keys.m("Company").tag()] });
    },
    ...options,
  });
}

export function useDeleteCompany(
  options?: UseMutationOptions<void, Error, string>,
) {
  const ctx = useFlowCtx();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { deleteCompany } = await import("../server/actions");
      return deleteCompany(id, ctx);
    },
    onSuccess: (data, id, context) => {
      queryClient.invalidateQueries({
        queryKey: keys.m("Company").byId(String(id)),
      });
      queryClient.invalidateQueries({ queryKey: [keys.m("Company").tag()] });
      options?.onSuccess?.(data, id, context);
    },
    ...options,
  });
}

export function useCompanyMutation(options?: {
  mode: "create" | "update";
  id?: string;
  onSuccess?: (data: FlowCompany) => void;
  onError?: (error: Error) => void;
}) {
  const { mode = "create", id, onSuccess, onError } = options || {};

  const createMutation = useCreateCompany({
    onSuccess,
    onError,
  });

  const updateMutation = useUpdateCompany(id!, {
    onSuccess,
    onError,
  });

  if (mode === "update" && id) {
    return updateMutation;
  }

  return createMutation as typeof createMutation;
}
