// @generated by next-prisma-flow-state-engine
// file: types/transforms.ts

import type { Prisma } from "../../prisma";
import type { FlowTagCreate, FlowTagUpdate } from "./schemas";

export function transformTagCreate(
  input: FlowTagCreate,
): Prisma.TagCreateInput {
  const result: any = {};

  result.name = input.name;
  if ("color" in input && input.color !== undefined) {
    result.color = input.color;
  }
  if ("createdAt" in input && input.createdAt !== undefined) {
    result.createdAt = input.createdAt;
  }
  if (input.company !== undefined) {
    const companyData = input.company;
    if (companyData) {
      if ("connect" in companyData && companyData.connect) {
        result.company = { connect: companyData.connect };
      } else if ("create" in companyData && companyData.create) {
        result.company = { create: companyData.create as any };
      } else if (
        "connectOrCreate" in companyData &&
        companyData.connectOrCreate
      ) {
        result.company = {
          connectOrCreate: companyData.connectOrCreate as any,
        };
      }
    }
  }
  // Handle foreign key field when relation is not provided
  if (input.company === undefined && "companyId" in input && input.companyId) {
    result.company = { connect: { id: input.companyId } };
  }
  if (input.todos !== undefined) {
    const todosData = input.todos;
    if (todosData) {
      if ("connect" in todosData && todosData.connect) {
        result.todos = { connect: todosData.connect };
      } else if ("create" in todosData && todosData.create) {
        result.todos = {
          create: todosData.create as any,
        };
      } else if ("createMany" in todosData && todosData.createMany) {
      } else if ("connectOrCreate" in todosData && todosData.connectOrCreate) {
        result.todos = {
          connectOrCreate: todosData.connectOrCreate as any,
        };
      }
    }
  }

  return result;
}

export function transformTagUpdate(
  input: FlowTagUpdate,
): Prisma.TagUpdateInput {
  const result: any = {};

  const nameValue = input.name;
  if (nameValue !== undefined && nameValue !== null) {
    result.name = nameValue;
  }
  const colorValue = input.color;
  if (colorValue !== undefined && colorValue !== null) {
    result.color = colorValue;
  }
  const createdAtValue = input.createdAt;
  if (createdAtValue !== undefined && createdAtValue !== null) {
    result.createdAt = createdAtValue;
  }
  if (input.company !== undefined) {
    const companyData = input.company;
    if (companyData) {
      result.company = companyData as any;
    }
  }
  if (input.todos !== undefined) {
    const todosData = input.todos;
    if (todosData) {
      result.todos = todosData as any;
    }
  }

  return result;
}
