// @generated by next-prisma-flow-state-engine
// file: server/actions.ts

"use server";

import { prisma } from "../../prisma";
import {
  invalidateTags,
  keys,
  FlowCtx,
  FlowPolicyError,
  FlowValidationError,
} from "../../core";
import { canUser } from "../../policies";
import { UserSelect } from "./selects";
import { UserCreateSchema, UserUpdateSchema } from "../types/schemas";
import type { FlowUserCreate, FlowUserUpdate } from "../types/schemas";
import { transformUserCreate, transformUserUpdate } from "../types/transforms";

// Transform Prisma response to match FlowPost schema (null -> undefined for relations)
function transformResponse(item: any): any {
  if (!item) return item;
  const result = { ...item };
  return result;
}

export async function createUser(data: FlowUserCreate, ctx: FlowCtx = {}) {
  const policy = await canUser("create", ctx || {});
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const parsed = UserCreateSchema.safeParse(data);
  if (!parsed.success) {
    throw new FlowValidationError(parsed.error.issues);
  }

  const createData = transformUserCreate(parsed.data as any);
  const item = await prisma.user.create({
    data: { ...createData, ...policy.data },
    select: UserSelect,
  });

  await invalidateTags([keys.m("User").tag()]);
  return transformResponse(item);
}

export async function updateUser(
  id: string,
  data: FlowUserUpdate,
  ctx: FlowCtx = {},
) {
  const policy = await canUser("update", ctx || {}, id);
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  const parsed = UserUpdateSchema.safeParse(data);
  if (!parsed.success) {
    throw new FlowValidationError(parsed.error.issues);
  }

  const updateData = transformUserUpdate(parsed.data as any);
  const item = await prisma.user.update({
    where: { id: id, ...policy.where },
    data: { ...updateData, ...policy.data },
    select: UserSelect,
  });

  await invalidateTags([keys.m("User").tag(), keys.m("User").tag(String(id))]);
  return transformResponse(item);
}

export async function deleteUser(id: string, ctx?: FlowCtx) {
  const policy = await canUser("delete", ctx || {}, id);
  if (!policy.ok) throw new FlowPolicyError(policy.message);

  await prisma.user.delete({
    where: { id: id, ...policy.where },
  });

  await invalidateTags([keys.m("User").tag(), keys.m("User").tag(String(id))]);
}
