// @generated by next-prisma-flow-state-engine
// file: index.ts

// Tree-shakeable named exports
export * as CommentServer from "./server";
export * as CommentClient from "./client";
export * as CommentTypes from "./types";

// Direct exports for common usage
export {
  // Hooks
  useComment,
  useCommentList,
  useCreateComment,
  useUpdateComment,
  useDeleteComment,
  useCommentMutation,
} from "./client/hooks";

export {
  // Forms
  useCommentForm,
  useCommentQuickForm,
  type CommentFormOptions,
  type CommentFormProps,
} from "./client/forms";

export {
  // Schemas
  CommentCreateSchema,
  CommentUpdateSchema,
  CommentFilterSchema,
  type FlowComment,
  type FlowCommentCreate,
  type FlowCommentUpdate,
  type FlowCommentFilter,
} from "./types/schemas";

export {
  // Types
  type CommentWithRelations,
  type CommentListItem,
  type CommentPage,
  type CommentCursor,
} from "./types/types";

// Server-only exports (for server components/actions)
export type { CommentListParams } from "./server/queries";
