// @generated by next-prisma-flow-state-engine
// file: core/keys.ts

export const keys = {
  m: (name: string) => ({
    byId: (id: string) => [name, "byId", id] as const,
    list: (p?: any) => [name, "list", p || {}] as const,
    tag: (sub?: string) => `${name}${sub ? ":" + sub : ""}`,
  }),
};
