// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-09T17:45:48.132Z

import { prisma } from "../prisma";
import type { SelectInput } from "./types";

export const model = "author" as const;
export const modelPrismaClient = prisma[model];
export const select: SelectInput = {
	id: true,
	email: true,
	name: true,
	avatar: true,
	createdAt: true,
	updatedAt: true,
};
