// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-13T11:36:20.954Z

import { useAtomValue, useSetAtom } from "jotai";
import { entityAtomFamily, errorAtom, pendingPatchesAtom } from "./atoms";
import {
	countAtom,
	countByFieldAtomFamily,
	entityBusyFamily,
	entityLoadableFamily,
	hasAnyAtom,
	listByFieldAtomFamily,
	listLoadable,
	loadingAtom,
	pagedAtom,
	searchAtom,
	selectedAtom,
	selectedIdAtom,
} from "./derived";

import { makeRelationHelpers } from "../shared/hooks/relation-helper";
import { createFormActions, makeUseFormHook, type UseFormOptions } from "../shared/hooks/use-form-factory";
import { useAutoload } from "../shared/hooks/useAutoload";
import { createAtom, deleteAtom, loadEntityAtom, loadsListAtom, updateAtom, upsertAtom } from "./fx";
import { schemas } from "./schemas";
import type { CreateInput, ModelType, Relationships, UpdateInput } from "./types";

/**
 * Hook for managing the complete authors collection with comprehensive state management.
 *
 * Provides access to the full authors list along with loading states, error handling,
 * and all necessary CRUD operations. This hook manages the global state for authors
 * and automatically handles loading indicators and error states.
 *
 * @param {Object} opts - Configuration options
 * @param {boolean} [opts.autoLoad=true] - Whether to automatically load data when component mounts
 *
 * @returns {Object} Complete authors management interface
 * @returns {Array} data - Array of authors (empty array when loading or on error)
 * @returns {number} count - Total number of authors available
 * @returns {boolean} hasAny - Quick check if any authors exist
 * @returns {boolean} loading - True when fetching data or performing operations
 * @returns {Error|null} error - Last error that occurred, null if no errors
 * @returns {Function} createAuthor - Creates a new author
 * @returns {Function} updateAuthor - Updates an existing author
 * @returns {Function} upsertAuthor - Upserts a author
 * @returns {Function} deleteAuthor - Deletes a author by ID
 * @returns {Function} fetchAll - Refreshes the entire authors list
 *
 * @example
 * ```tsx
 * function AuthorsList() {
 *   const { data, loading, error, createAuthor, updateAuthor, deleteAuthor } = useAuthors();
 *
 *   if (loading) return <div>Loading authors...</div>;
 *   if (error) return <div>Error: {error.message}</div>;
 *
 *   return (
 *     <div>
 *       {data.map(author => (
 *         <AuthorItem key={author.id} author={author} onUpdate={updateAuthor} onDelete={deleteAuthor} />
 *       ))}
 *     </div>
 *   );
 * }
 * ```
 */
export function useAuthors(opts: { autoLoad?: boolean } = { autoLoad: true }) {
	const loadable = useAtomValue(listLoadable);
	const busy = useAtomValue(loadingAtom);
	const count = useAtomValue(countAtom);
	const hasAny = useAtomValue(hasAnyAtom);
	const lastError = useAtomValue(errorAtom);

	const createAuthor = useSetAtom(createAtom);
	const updateAuthor = useSetAtom(updateAtom);
	const deleteAuthor = useSetAtom(deleteAtom);
	const upsertAuthor = useSetAtom(upsertAtom);
	const fetchAll = useSetAtom(loadsListAtom);
	const fetchById = useSetAtom(loadEntityAtom);

	useAutoload(
		() => opts.autoLoad !== false && !busy && !hasAny,
		() => fetchAll({}, {}),
	);

	return {
		/* data */
		data: loadable.state === "hasData" ? loadable.data : [],
		count,
		hasAny,

		/* meta */
		loading: busy || loadable.state === "loading",
		error: loadable.state === "hasError" ? loadable.error : lastError,

		/* actions */
		createAuthor,
		updateAuthor,
		deleteAuthor,
		upsertAuthor,
		fetchAll,
		fetchById,
	};
}

/**
 * Hook for managing a specific author by ID with optimistic updates and error handling.
 *
 * Provides granular control over individual authors, including fetching, updating, and deleting.
 * The hook automatically manages loading states and errors specific to this author instance.
 * Actions are pre-bound with the author ID for convenience.
 *
 * @param {string} id - The unique identifier of the author to manage
 * @param {Object} opts - Configuration options
 * @param {boolean} [opts.autoLoad=true] - Whether to automatically load data when component mounts
 *
 * @returns {Object} Single author management interface
 * @returns {Object|null} data - The author data object, null if not found or loading
 * @returns {boolean} loading - True when fetching or performing operations on this author
 * @returns {Error|null} error - Last error related to operations on this author
 * @returns {Function} updateAuthor - Updates this specific author with provided data
 * @returns {Function} deleteAuthor - Deletes this specific author
 * @returns {Function} fetch - Fetches/refreshes this specific author from the server
 * @returns {Object} relations - relationship helpers
 *
 * @example
 * ```tsx
 * function AuthorDetail({ authorId }: { authorId: string }) {
 *   const { data, loading, error, updateAuthor, deleteAuthor } = useAuthor(authorId);
 *
 *   if (loading) return <div>Loading author...</div>;
 *   if (error) return <div>Error loading author: {error.message}</div>;
 *   if (!data) return <div>Author not found</div>;
 *
 *   const handleSave = (formData) => {
 *     updateAuthor(formData); // ID is automatically included
 *   };
 *
 *   return (
 *     <div>
 *       <h1>{data.title}</h1>
 *       <p>{data.content}</p>
 *       <button onClick={() => deleteAuthor()}>Delete</button>
 *     </div>
 *   );
 * }
 * ```
 */
export function useAuthor(id: string, opts: { autoLoad?: boolean } = { autoLoad: true }) {
	const author = useAtomValue(entityAtomFamily(id));
	const loadable = useAtomValue(entityLoadableFamily(id));
	const busyItem = useAtomValue(entityBusyFamily(id));
	const lastError = useAtomValue(errorAtom);
	const pendingPatches = useAtomValue(pendingPatchesAtom);

	const updateAuthor = useSetAtom(updateAtom);
	const deleteAuthor = useSetAtom(deleteAtom);
	const fetch = useSetAtom(loadEntityAtom);

	const relations = makeRelationHelpers<Relationships>(id, updateAuthor);

	useAutoload(
		() => opts.autoLoad !== false && !busyItem && !author && !pendingPatches[id],
		() => fetch({ id }),
	);

	return {
		/* data */
		data: author,

		/* meta */
		loading: busyItem || loadable.state === "loading",
		error: lastError,

		/* actions */
		updateAuthor: (data: UpdateInput) => updateAuthor({ id, data }),
		deleteAuthor: () => deleteAuthor(id),
		fetch: () => fetch({ id }),

		/* relations */
		relations,
	};
}

/**
 * Enhanced form hook with integrated CRUD operations and optimistic updates.
 *
 * Automatically detects create vs update mode based on whether an instance is provided.
 * Integrates directly with the author atoms for seamless state management.
 *
 * @param {ModelType} [instance] - Author instance for update mode, undefined for create mode
 * @param {Object} [options] - Form options and callbacks
 * @param {Function} [options.onSuccess] - Callback fired on successful submission
 * @param {Function} [options.onError] - Callback fired on submission error
 * @param {boolean} [options.resetOnSuccess=true] - Whether to reset form after successful creation
 * @param {Object} [options.transform] - Data transformation functions
 *
 * @returns {Object} Enhanced form interface with submission handling
 * @returns {Function} handleSubmit - Form submission handler
 * @returns {boolean} isSubmitting - Whether form is currently submitting
 * @returns {boolean} isCreating - Whether form is in create mode and submitting
 * @returns {boolean} isUpdating - Whether form is in update mode and submitting
 * @returns {string} mode - Current form mode: 'create' | 'update'
 * @returns {any} submitError - Last submission error, if any
 * @returns {*} ...formMethods - All react-hook-form methods and state
 *
 * @example
 * ```tsx
 * function AuthorForm({ author, onClose }) {
 *   const form = useAuthorForm(author, {
 *     onSuccess: () => onClose(),
 *     onError: (error) => toast.error(error.message),
 *     transform: {
 *       toCreateInput: (data) => ({
 *         ...data,
 *         authorId: data.author?.id || data.authorId,
 *         categoryId: data.category?.id || data.categoryId,
 *       }),
 *     },
 *   });
 *
 *   return (
 *     <form onSubmit={form.handleSubmit}>
 *       <input {...form.register('title')} placeholder="Title" />
 *       <textarea {...form.register('description')} placeholder="Description" />
 *       <button type="submit" disabled={form.isSubmitting}>
 *         {form.isSubmitting
 *           ? (form.mode === 'create' ? 'Creating...' : 'Updating...')
 *           : (form.mode === 'create' ? 'Create Author' : 'Update Author')
 *         }
 *       </button>
 *     </form>
 *   );
 * }
 * ```
 */
export function useAuthorForm(instance?: ModelType, options: UseFormOptions<ModelType> = {}) {
	const createAuthorAction = useSetAtom(createAtom);
	const updateAuthorAction = useSetAtom(updateAtom);

	const formActions = createFormActions(createAuthorAction, updateAuthorAction);

	return makeUseFormHook<ModelType, CreateInput, UpdateInput>(
		{
			create: schemas.createInput,
			update: schemas.updateInput,
		},
		formActions,
	)(instance, options);
}

export const useSelectedId = () => useAtomValue(selectedIdAtom);
export const useSelected = () => useAtomValue(selectedAtom);
export const useSetSelectedId = () => useSetAtom(selectedIdAtom);

export function useListByFieldValue<K extends keyof ModelType>(field: K, value: ModelType[K]) {
	const fam = listByFieldAtomFamily(field);
	return useAtomValue(fam(value));
}

export function usePagedList(page: number, pageSize = 10) {
	return useAtomValue(pagedAtom({ page, pageSize }));
}

export function useSearch(query: string) {
	return useAtomValue(searchAtom(query));
}

export function useCountByFieldValue<K extends keyof ModelType>(field: K, value: ModelType[K]) {
	const fam = countByFieldAtomFamily(field);
	return useAtomValue(fam(value));
}
