// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-09T17:45:48.132Z

import {
	AuthorCreateInputSchema,
	AuthorCreateManyInputSchema,
	AuthorFindFirstArgsSchema,
	AuthorFindManyArgsSchema,
	AuthorUpdateInputSchema,
	AuthorWhereInputSchema,
	AuthorWhereUniqueInputSchema,
} from "../zod";

export const schemas = {
	whereUnique: AuthorWhereUniqueInputSchema,
	where: AuthorWhereInputSchema,
	createInput: AuthorCreateInputSchema,
	createManyInput: AuthorCreateManyInputSchema,
	updateInput: AuthorUpdateInputSchema,
	findFirstArgs: AuthorFindFirstArgsSchema,
	findManyArgs: AuthorFindManyArgsSchema,
	// Adding create and update for form factory compatibility
	create: AuthorCreateInputSchema,
	update: AuthorUpdateInputSchema,
};
