// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-08-01T17:20:41.596Z

import {
	AuthorCreateManyInputSchema,
	AuthorFindFirstArgsSchema,
	AuthorFindManyArgsSchema,
	AuthorUncheckedCreateInputSchema,
	AuthorUncheckedUpdateInputSchema,
	AuthorWhereInputSchema,
	AuthorWhereUniqueInputSchema,
} from "../zod";

export const schemas = {
	whereUnique: AuthorWhereUniqueInputSchema,
	where: AuthorWhereInputSchema,
	createInput: AuthorUncheckedCreateInputSchema,
	createManyInput: AuthorCreateManyInputSchema,
	updateInput: AuthorUncheckedUpdateInputSchema,
	findFirstArgs: AuthorFindFirstArgsSchema,
	findManyArgs: AuthorFindManyArgsSchema,
};
