// This file is auto-generated by Next Prisma Flow Generator.
// Do not edit this file manually as it will be overwritten.
// Generated at: 2025-06-09T17:45:48.132Z

import type { Prisma } from "../prisma";

export type CreateInput = Prisma.AuthorCreateInput;
export type CreateManyInput = Prisma.AuthorCreateManyInput;
export type UpdateInput = Prisma.AuthorUpdateInput;
export type UpdateManyInput = Prisma.AuthorUncheckedUpdateManyInput;
export type WhereInput = Prisma.AuthorWhereInput;
export type WhereUniqueInput = Prisma.AuthorWhereUniqueInput;
export type OrderByInput = Prisma.AuthorOrderByWithRelationInput;
export type SelectInput = Prisma.AuthorSelect;
export type IncludeInput = Prisma.AuthorInclude;

export type ModelType = Prisma.AuthorGetPayload<{
	select: {
		id: true;
		email: true;
		name: true;
		avatar: true;
		createdAt: true;
		updatedAt: true;
	};
}>;

export type Options = {
	orderBy?: OrderByInput;
};

export type CreateManyOptions = {
	include?: IncludeInput;
	select?: SelectInput;
};

export interface Relationships extends Record<string, { where: any; many: boolean }> {
	// No relationships found for this model
}
