// @generated by next-prisma-flow-state-engine
// file: index.ts

// Tree-shakeable named exports
export * as PostServer from "./server";
export * as PostClient from "./client";
export * as PostTypes from "./types";

// Direct exports for common usage
export {
  // Hooks
  usePost,
  usePostList,
  useCreatePost,
  useUpdatePost,
  useDeletePost,
  usePostMutation,
} from "./client/hooks";

export {
  // Forms
  usePostForm,
  usePostQuickForm,
  type PostFormOptions,
  type PostFormProps,
} from "./client/forms";

export {
  // Schemas
  PostCreateSchema,
  PostUpdateSchema,
  PostFilterSchema,
  type FlowPost,
  type FlowPostCreate,
  type FlowPostUpdate,
  type FlowPostFilter,
} from "./types/schemas";

export {
  // Types
  type PostWithRelations,
  type PostListItem,
  type PostPage,
  type PostCursor,
} from "./types/types";

// Server-only exports (for server components/actions)
export type { PostListParams } from "./server/queries";
